package api

import (
	"encoding/json"
	"fmt"
	"io"
	"math"
	"net/http"
	"regexp"
	"sort"
	"strconv"
	"strings"
	"time"

	"github.com/Arjun0606/smolanalytics/internal/brief"
	"github.com/Arjun0606/smolanalytics/internal/event"
	"github.com/Arjun0606/smolanalytics/internal/funnel"
	"github.com/Arjun0606/smolanalytics/internal/query"
	"github.com/Arjun0606/smolanalytics/internal/retention"
	"github.com/Arjun0606/smolanalytics/internal/trends"
)

// ask answers a plain-English question about the data with zero dependencies,
// it routes common questions (conversion, retention, signups, channels, active
// users, the weekly brief) deterministically, right in the dashboard, no model
// required. For arbitrary questions the user connects smolanalytics to their
// OWN Claude / Cursor over MCP (we never call a model ourselves), see internal/mcp.
func (s *Server) ask(w http.ResponseWriter, r *http.Request) {
	body, _ := io.ReadAll(io.LimitReader(r.Body, 1<<20))
	var req struct {
		Question string `json:"question"`
	}
	_ = json.Unmarshal(body, &req)
	q := strings.ToLower(strings.TrimSpace(req.Question))
	if q == "" {
		writeErr(w, http.StatusBadRequest, "ask a question")
		return
	}
	evs, err := s.store.Range(time.Time{}, time.Time{})
	if err != nil {
		writeErr(w, http.StatusInternalServerError, err.Error())
		return
	}
	evs = query.Apply(evs, nil) // production scope: dev-env events excluded by default

	now := time.Now().UTC()
	// every answer ships with its receipt: which deterministic report produced it, over
	// what window, and the guarantee that a CI test proves it can't be fabricated. "Plain
	// English analytics" makes people fear hallucinated numbers — show the work so they can
	// verify before they trust. The intent is the deterministic route the classifier picked,
	// exposed so a UI can render the matching chart under the answer (reports-as-answers)
	// without re-classifying the question and drifting from the engine.
	// a refusal (unsupported time window) must return NO intent: the UIs chart by
	// intent, and a chart under "I can't answer that" reads as an answer anyway —
	// the exact incoherence the proof chip exists to prevent.
	intent := string(classifyAsk(q))
	if _, unsupported := parseWindow(q, now); unsupported != "" {
		intent = ""
	}
	writeJSON(w, http.StatusOK, map[string]string{
		"answer":      answer(q, evs, now),
		"computed_by": computedBy(q, now),
		"intent":      intent,
	})
}

// computedBy is the "show your work" receipt for an answer: the exact deterministic
// report + scope behind it, plus the trust guarantee. Read-only, so a founder can sanity
// check the method before trusting the number.
func computedBy(q string, now time.Time) string {
	if isAction(q) {
		return "" // action asks aren't data answers
	}
	win, _ := parseWindow(q, now)
	scope := "all recorded events"
	if win.scoped() && win.label != "" {
		scope = strings.TrimSpace(win.label)
	}
	if classifyAsk(q) == intentUnknown {
		return "You asked about something with no matching event, so nothing was fabricated. I showed the weekly pulse instead, computed deterministically. Send that metric as an event and I'll report it."
	}
	var report string
	switch classifyAsk(q) {
	case intentBrief:
		report = "the verdict engine (notable-change detection + the weekly pulse)"
	case intentFunnel:
		report = "the funnel report"
	case intentChannels:
		report = "the first-touch channel-attribution report"
	case intentRetention:
		report = "the retention report"
	case intentActive:
		report = "the active-users report"
	case intentSignups:
		report = "the event-trend report"
	case intentWeb:
		report = "the web-overview report"
	case intentTopPages:
		report = "the top-pages report"
	case intentGeo:
		report = "the geo (countries) breakdown of the web-overview report"
	case intentMeasure:
		report = "the numeric-aggregation report (a deterministic sum/avg/median/p90 over a property you sent)"
	default:
		report = "a deterministic report"
	}
	return "Computed by " + report + " over " + scope + ", the same engine the dashboard runs, not generated by a model. A CI test asserts this number equals the dashboard's report, so it cannot be fabricated. Open that report on the dashboard to verify."
}

// askIntent is the deterministic route the ask bar picked for a question, a
// named type (not bare strings) so the router and its tests cannot drift apart.
type askIntent string

const (
	intentAction    askIntent = "action"
	intentBrief     askIntent = "brief"
	intentRetention askIntent = "retention"
	intentChannels  askIntent = "channels"
	intentGeo       askIntent = "geo"
	intentTopPages  askIntent = "toppages"
	intentWeb       askIntent = "web"
	intentFunnel    askIntent = "funnel"
	intentActive    askIntent = "active"
	intentSignups   askIntent = "signups"
	intentMeasure   askIntent = "measure"
	intentUnknown   askIntent = "unknown"
)

// classifyAsk routes a lowercased question to one intent. Order is the whole
// game: action-y asks must never fall through to a metric ("alert me if signups
// drop" mentions both), and specific phrasings outrank generic keywords,
// "which channel converts best" is a channel question, not a funnel one, and
// "how many active users" is a user count, not a signup trend.
func classifyAsk(q string) askIntent {
	switch {
	case isAction(q):
		return intentAction
	// "what should I fix" is the product's own tagline — it, and every health-check
	// phrasing, must land on the verdict, never the capabilities menu.
	case hasAny(q, "how are things", "how's it going", "how is it going", "what happened",
		"weekly report", "week in review", "summary", "overview", "digest", "brief",
		"what should i fix", "what to fix", "needs fixing", "fix first", "broken",
		"what's wrong", "whats wrong", "going wrong", "wrong with", "problem",
		"needs attention", "what should i do", "priorit", "red flag", "biggest issue"):
		return intentBrief
	// numeric aggregation (revenue = sum of amount, AOV = avg, p90 latency) BEFORE the
	// count-y intents, so "total revenue"/"average order value" aren't answered as a
	// checkout count. Resolves to a real number only if the property was actually sent.
	case isMeasureAsk(q):
		return intentMeasure
	case hasAny(q, "retention", "retain", "come back", "comeback", "returning", "stick"):
		return intentRetention
	// top-pages must outrank both channels ("which pages" ≠ "which sources") and the
	// web-volume case below.
	case hasAny(q, "top page", "top pages", "most visited", "popular page", "most viewed",
		"which page", "best page", "top url", "top path", "top content"):
		return intentTopPages
	// geo = country questions. Before channels so "how many countries" and "which
	// countries" never land on sources or a signup trend.
	case hasAny(q, "countr", "geograph", "which nations", "around the world", "worldwide"):
		return intentGeo
	// channels = WHERE traffic comes from (sources), not how much of it there is.
	case hasAny(q, "channel", "source", "acquisition", "referr", "utm", "campaign",
		"come from", "coming from", "came from", "where do my", "where are my visitors"):
		return intentChannels
	// web volume = pageviews / visitors / traffic counts. After channels so "where do
	// visitors come from" stays a channel question, but BEFORE signups so "how many
	// pageviews" is never answered as a signup count (the confidently-wrong bug).
	case hasAny(q, "pageview", "page view", "traffic", "visits", "visitor", "unique visitor",
		"how many views"):
		return intentWeb
	case hasAny(q, "convert", "conversion", "funnel", "drop", "checkout", "activat"):
		return intentFunnel
	case hasAny(q, "active", "dau", "wau", "total users", "how many users", "user count"):
		return intentActive
	case hasAny(q, "signup", "sign up", "sign-up", "new user", "growth", "trend", "how many"):
		return intentSignups
	default:
		return intentUnknown
	}
}

// isAction spots asks that want to CHANGE something. The ask bar is read-only,
// these must never come back as a metric that pretends the change happened.
func isAction(q string) bool {
	if hasAny(q, "alert", "notify", "rename", "configure", "turn on", "turn off",
		"retention to", "set retention", "change retention") {
		return true
	}
	for _, verb := range []string{"set ", "change ", "enable ", "disable ", "delete ",
		"create ", "add ", "save ", "update ", "remove "} {
		if strings.HasPrefix(q, verb) {
			return true
		}
	}
	return false
}

func answer(q string, evs []event.Event, now time.Time) string {
	intent := classifyAsk(q)
	switch intent {
	case intentAction:
		return answerAction(q)
	case intentBrief:
		return answerBrief(evs, briefDays(q), now)
	}

	win, unsupported := parseWindow(q, now)
	if unsupported != "" {
		return fmt.Sprintf("I can't scope to %q from the ask bar, supported windows: today, yesterday, "+
			"this/last week, this/last month, and \"last N days\". Re-ask with one of those, or drop the "+
			"time phrase for all recorded history. For arbitrary ranges, ask your agent over MCP, the "+
			"trends and funnel tools take exact dates.", unsupported)
	}
	volAll := eventsByVolume(evs) // event NAMES come from the full schema, metrics from the window
	scoped := scope(evs, win)

	// Numeric aggregation wins before the path/event-name shortcuts, so "average order
	// value" isn't hijacked into a checkout COUNT by the named-event branch below.
	if intent == intentMeasure {
		return answerMeasure(scoped, q, volAll, win)
	}

	// Explicit page-path or event-name mentions answer about exactly what the user named,
	// taking priority over the generic intents. This is what lets the "your pages" and
	// "your events" discovery chips resolve to a real answer instead of a generic one, and
	// what makes "visitors to /pricing" and "how many checkout this week" just work.
	if path := extractPath(q); path != "" {
		return answerPage(scoped, path, win)
	}
	if ev := namedEvent(q, volAll); ev != "" && countish(q) {
		return answerEvent(scoped, ev, win)
	}
	// If the user explicitly named an event ("the X event", "X events fire") that we
	// DON'T have, say so with the nearest real name — never silently fall through to a
	// default event and hand back an authoritative count for something they didn't ask
	// about. That substitution is the exact "trust your numbers" failure this product
	// sells against.
	if miss := unknownNamedEvent(q, volAll); miss != "" {
		return answerUnknownEvent(miss, volAll)
	}

	switch intent {
	case intentRetention:
		return answerRetention(scoped, volAll, win, now, q)
	case intentChannels:
		return answerChannels(scoped, volAll, win)
	case intentTopPages:
		return answerTopPages(scoped, win)
	case intentGeo:
		return answerGeo(scoped, evs, win)
	case intentWeb:
		return answerWeb(scoped, win)
	case intentFunnel:
		return answerFunnel(scoped, volAll, win)
	case intentActive:
		return answerActive(scoped, win, now)
	case intentSignups:
		return answerSignups(scoped, volAll, win)
	default:
		// An unrecognized question must NAME the boundary before answering — refusing to
		// fabricate a metric we don't have is the single strongest trust move on the demo.
		// "what's my MRR?" silently returning a weekly digest reads exactly like a model
		// padding an answer, the very fear "plain-English analytics" triggers. So we say
		// what we don't invent, then offer the closest real report.
		return "I only answer from deterministic reports over the events you've sent, funnels, channels, " +
			"retention, signups, active users, top pages, pageviews. I don't invent metrics you haven't " +
			"tracked (revenue, MRR, churn) unless you send them as events. Here's the closest read I have:\n\n" +
			answerBrief(evs, 7, now) + "\n\nAsk about any of those, scoped to today, yesterday, this/last week, " +
			"this/last month, or last N days, or connect your own Claude/Cursor over MCP to go deeper."
	}
}

// isMeasureAsk spots a numeric-aggregation question (revenue, AOV, median, p90) vs a count.
// Kept to STRONG signals so "how much traffic" stays a web question, not a measure.
func isMeasureAsk(q string) bool {
	if hasAny(q, "revenue", "order value", "aov", "arpu", "sum of", "median",
		"percentile", "p90", "p95", "p99", "average", "avg ", "mean ",
		"how much money", "how much did", "total spend", "total amount", "total revenue") {
		return true
	}
	// superlatives count as a measure only when paired with a value-ish word, so "max amount"
	// / "highest revenue" route to a measure but "highest traffic" stays a web question.
	return hasAny(q, "highest", "lowest", "max ", "maximum", "minimum", "min ", "biggest", "largest", "smallest", "peak ") &&
		hasAny(q, "amount", "revenue", "value", "price", "cost", "spend", "order", "cart", "duration", "latency", "load time", "response time", "payment", "purchase")
}

// measureFromQuestion picks the aggregation from the phrasing; defaults to Sum (revenue).
func measureFromQuestion(q string) trends.Measure {
	switch {
	case hasAny(q, "average", "avg", "mean", "order value", "aov", "arpu"):
		return trends.Avg
	case hasAny(q, "median"):
		return trends.Median
	case hasAny(q, "p90", "p95", "p99", "percentile", "90th"):
		return trends.P90
	case hasAny(q, "highest", "max", "biggest", "largest", "peak"):
		return trends.Max
	case hasAny(q, "lowest", "min", "smallest"):
		return trends.Min
	default:
		return trends.Sum
	}
}

// resolveNumericProp maps the question to a numeric property that ACTUALLY EXISTS in the
// events, so we never invent a metric. Direct name match first, then aliases, then the usual
// money columns. Returns "" when nothing numeric fits — the honest-refusal path.
func resolveNumericProp(q string, evs []event.Event) string {
	props := trends.NumericProps(evs)
	if len(props) == 0 {
		return ""
	}
	has := func(name string) bool {
		for _, p := range props {
			if p == name {
				return true
			}
		}
		return false
	}
	for _, p := range props { // 1. a real numeric property named verbatim
		if strings.Contains(q, strings.ToLower(p)) {
			return p
		}
	}
	for _, a := range [][2]string{ // 2. aliases -> a candidate that exists
		{"revenue", "amount"}, {"order value", "amount"}, {"aov", "amount"}, {"sales", "amount"},
		{"spend", "amount"}, {"money", "amount"}, {"arpu", "amount"},
		{"latency", "duration_ms"}, {"load time", "duration_ms"}, {"duration", "duration_ms"},
		{"response time", "duration_ms"},
	} {
		if strings.Contains(q, a[0]) && has(a[1]) {
			return a[1]
		}
	}
	for _, c := range []string{"amount", "revenue", "value", "total", "price"} { // 3. usual columns
		if has(c) {
			return c
		}
	}
	return ""
}

// answerMeasure computes a numeric aggregate over a real property, or refuses honestly when
// no such property was sent — never fabricating a metric (the core trust promise).
func answerMeasure(evs []event.Event, q string, volAll []string, win askWindow) string {
	m := measureFromQuestion(q)
	prop := resolveNumericProp(q, evs)
	if prop == "" {
		if props := trends.NumericProps(evs); len(props) > 0 {
			return "I compute numbers only from values you've actually sent, so I won't invent one. The numeric properties on your events are: " +
				strings.Join(props, ", ") + ". Ask about one of those, or send a new one (e.g. track(\"checkout\", {amount: 29}))."
		}
		return "I compute numbers only from values you've actually sent, so I won't invent one. You haven't sent any numeric event properties yet — add one (e.g. track(\"checkout\", {amount: 29})) and I'll total or average it exactly."
	}
	ev := namedEvent(q, volAll) // "" = across every event carrying the property
	res := trends.ComputeMeasure(evs, ev, prop, m, win.from, win.to)
	if res.N == 0 {
		return fmt.Sprintf("No numeric %q values in that window yet, so there's nothing to compute. Once your events carry it, I'll report it exactly.", prop)
	}
	verb := map[trends.Measure]string{trends.Sum: "Total", trends.Avg: "Average", trends.Min: "Minimum", trends.Max: "Maximum", trends.Median: "Median", trends.P90: "p90"}[m]
	evPart := ""
	if ev != "" {
		evPart = " per " + ev
	}
	scopePart := ""
	if win.scoped() && win.label != "" {
		scopePart = ", " + strings.TrimSpace(win.label)
	}
	plural := "s"
	if res.N == 1 {
		plural = ""
	}
	return fmt.Sprintf("%s %s%s%s: %s, computed from %d event%s.", verb, prop, evPart, scopePart, fmtMeasureNum(res.Total), res.N, plural)
}

// fmtMeasureNum prints a whole number cleanly and anything else to 2 decimals.
func fmtMeasureNum(f float64) string {
	if f == math.Trunc(f) {
		return strconv.FormatFloat(f, 'f', 0, 64)
	}
	return strconv.FormatFloat(f, 'f', 2, 64)
}

// answerAction is honest guidance for change requests: the ask bar computes
// answers, it does not flip switches. Every branch names where the change
// actually lives, the Settings section and the MCP tool an agent can call.
func answerAction(q string) string {
	switch {
	case hasAny(q, "alert", "notify", "watch"):
		return "I can't create alerts from here, the ask bar only reads data. Set one up in Settings → Alerts " +
			"(wire a Slack/HTTPS destination under Settings → Webhooks first). In Cursor/Claude Code your " +
			"agent can do it directly: create_alert (\"tell me if signups drop below 10/day\")."
	case hasAny(q, "retention", "retain"):
		return "I can't change settings from here, data retention lives in Settings → Retention. " +
			"In Cursor/Claude Code your agent can: set_retention."
	case strings.Contains(q, "rename"):
		return "I can't rename events from here, event names come from your instrumentation. Rename it where " +
			"you call track(), then declare the new name in your tracking plan (set_tracking_plan in " +
			"Cursor/Claude Code) so drift gets flagged under Settings → Events tracked."
	default:
		return "The ask bar computes answers from your data, it can't change anything. Settings has the knobs " +
			"(retention, alerts, webhooks, API keys), and in Cursor/Claude Code your agent has the action " +
			"tools: create_alert, set_retention, create_goal, save_report."
	}
}

// briefDays maps the ask's phrasing to the brief's pulse width: "today" → 1,
// month phrasing → 30, else the weekly 7. brief.Build derives the
// current-vs-prior comparison windows from this.
func briefDays(q string) int {
	switch {
	case strings.Contains(q, "today"):
		return 1
	case strings.Contains(q, "month"):
		return 30
	default:
		return 7
	}
}

// answerBrief renders the SAME computation as `smolanalytics brief` (pulse +
// deltas + the verdict engine's findings) tight enough for the ask panel, one
// Brief struct feeds both, so the ask bar and the morning digest can never disagree.
func answerBrief(evs []event.Event, days int, now time.Time) string {
	b := brief.Build(evs, days, now)
	var s strings.Builder
	fmt.Fprintf(&s, "Last %d days: %d visitors · %d events", b.Days, b.Visitors, b.Events)
	if b.PriorEvents == 0 {
		s.WriteString(" (no prior window to compare).")
	} else {
		visitors := "new"
		if b.PriorVisitors > 0 {
			visitors = fmt.Sprintf("%+d%%", pctChange(b.Visitors, b.PriorVisitors))
		}
		fmt.Fprintf(&s, " (vs prior %d days: visitors %s, events %+d%%).", b.Days,
			visitors, pctChange(b.Events, b.PriorEvents))
	}
	if len(b.Findings) == 0 {
		s.WriteString(" Nothing notable, no big swings, funnel leaks, or retention flags.")
		return s.String()
	}
	s.WriteString("\nWhat to look at:")
	for _, f := range b.Findings {
		mark := "•"
		if f.Severity == "warn" {
			mark = "⚠"
		}
		fmt.Fprintf(&s, "\n%s %s, %s", mark, f.Title, f.Detail)
	}
	return s.String()
}

// pctChange mirrors brief's signed delta, direction must be unmissable.
func pctChange(cur, prior int) int {
	return int(math.Round(float64(cur-prior) / float64(prior) * 100))
}

// askWindow is an honest time scope parsed from the question. Zero from/to =
// all recorded history (the ask bar's long-standing default). The label is
// woven into every scoped answer so "this week" can never silently mean
// something else.
type askWindow struct {
	from, to time.Time
	label    string
}

func (w askWindow) scoped() bool { return !w.from.IsZero() || !w.to.IsZero() }

// windowClause weaves the computed window into a sentence: " this week (since
// Mon Jun 22, UTC)", or "" for all-time.
func windowClause(w askWindow) string {
	if !w.scoped() {
		return ""
	}
	return " " + w.label
}

var lastNDaysRe = regexp.MustCompile(`(?:last|past)\s+(\d+)\s+days?`)

// parseWindow maps time phrases to real windows (UTC, like every computation
// here). Recognized: today, yesterday, this/last week (calendar, Monday start),
// this/last month (calendar), and "last/past N days" (rolling, consistent with
// the engine). Anything else time-shaped (quarters, years, named months) comes
// back as unsupported so the caller can SAY so instead of silently answering
// over a different range.
func parseWindow(q string, now time.Time) (win askWindow, unsupported string) {
	const day = 24 * time.Hour
	today := now.Truncate(day)
	switch {
	case strings.Contains(q, "yesterday"):
		return askWindow{from: today.Add(-day), to: today, label: "yesterday (UTC)"}, ""
	case strings.Contains(q, "today"):
		return askWindow{from: today, to: now, label: "today (UTC)"}, ""
	case strings.Contains(q, "this week"):
		monday := today.AddDate(0, 0, -mondayOffset(today))
		return askWindow{from: monday, to: now,
			label: "this week (since Mon " + monday.Format("Jan 2") + ", UTC)"}, ""
	case strings.Contains(q, "last week"):
		monday := today.AddDate(0, 0, -mondayOffset(today))
		from := monday.AddDate(0, 0, -7)
		return askWindow{from: from, to: monday,
			label: "last week (Mon " + from.Format("Jan 2") + " – Sun " + monday.AddDate(0, 0, -1).Format("Jan 2") + ", UTC)"}, ""
	case strings.Contains(q, "past week"), strings.Contains(q, "previous week"):
		return askWindow{from: now.AddDate(0, 0, -7), to: now, label: "the last 7 days (UTC)"}, ""
	case strings.Contains(q, "past month"), strings.Contains(q, "previous month"):
		return askWindow{from: now.AddDate(0, 0, -30), to: now, label: "the last 30 days (UTC)"}, ""
	case strings.Contains(q, "this month"):
		first := time.Date(now.Year(), now.Month(), 1, 0, 0, 0, 0, time.UTC)
		return askWindow{from: first, to: now,
			label: "this month (since " + first.Format("Jan 2") + ", UTC)"}, ""
	case strings.Contains(q, "last month"):
		first := time.Date(now.Year(), now.Month(), 1, 0, 0, 0, 0, time.UTC)
		return askWindow{from: first.AddDate(0, -1, 0), to: first,
			label: "last month (" + first.AddDate(0, -1, 0).Format("January 2006") + ", UTC)"}, ""
	}
	if m := lastNDaysRe.FindStringSubmatch(q); m != nil {
		if n, err := strconv.Atoi(m[1]); err == nil && n > 0 {
			return askWindow{from: now.AddDate(0, 0, -n), to: now,
				label: fmt.Sprintf("the last %d days (UTC)", n)}, ""
		}
	}
	if tok := unsupportedTimePhrase(q); tok != "" {
		return askWindow{}, tok
	}
	return askWindow{}, ""
}

// mondayOffset is days since the most recent Monday (0 on a Monday), Go's
// time.Weekday puts Sunday at 0, one off from a Monday-start week.
func mondayOffset(t time.Time) int { return (int(t.Weekday()) + 6) % 7 }

// unsupportedTimePhrase returns the first time-shaped token the parser does NOT
// support, so the answer can name it instead of quietly widening the window.
func unsupportedTimePhrase(q string) string {
	for _, tok := range []string{"quarter", "year", "month", "week", "hour", "minute",
		"q1", "q2", "q3", "q4", "january", "february", "march", "april", "june", "july",
		"august", "september", "october", "november", "december"} {
		if containsWord(q, tok) {
			return tok
		}
	}
	return ""
}

// containsWord reports whether tok appears as a whole word, "month" must not
// fire on "monthly", or every trend question would bounce as an unsupported window.
func containsWord(q, tok string) bool {
	isSep := func(r rune) bool { return !('a' <= r && r <= 'z' || '0' <= r && r <= '9') }
	for _, w := range strings.FieldsFunc(q, isSep) {
		if w == tok {
			return true
		}
	}
	return false
}

// scope keeps events inside [from, to), the end is exclusive so "yesterday"
// and "last week" never double-count the boundary instant.
func scope(evs []event.Event, w askWindow) []event.Event {
	if !w.scoped() {
		return evs
	}
	out := make([]event.Event, 0, len(evs))
	for _, e := range evs {
		if !w.from.IsZero() && e.Timestamp.Before(w.from) {
			continue
		}
		if !w.to.IsZero() && !e.Timestamp.Before(w.to) {
			continue
		}
		out = append(out, e)
	}
	return out
}

func answerFunnel(evs []event.Event, vol []string, win askWindow) string {
	fsteps, ftitle := detectFunnel(evs, vol)
	fr := funnel.Compute(evs, fsteps, 7*24*time.Hour)
	if len(fr.Steps) == 0 || fr.Steps[0].Count == 0 {
		if win.scoped() {
			return "No events " + win.label + " to build a funnel from, widen the window, or drop the time phrase for all history."
		}
		return "No events yet to build a funnel from."
	}
	if len(fr.Steps) < 2 {
		// a single distinct event name means there's no funnel to measure yet, a bare
		// "signup → signup" would print an empty drop-off step with a -1 count. Answer
		// honestly and name the next action instead.
		return fmt.Sprintf("%d users did %q%s, that's the only event type tracked, so there's no funnel to measure yet. Add a later step (activate, checkout) to see where users drop off.",
			fr.Steps[0].Count, fr.Steps[0].Event, windowClause(win))
	}
	worst, worstDrop := "", -1
	for _, st := range fr.Steps[1:] {
		if st.DroppedFromPrev > worstDrop {
			worstDrop, worst = st.DroppedFromPrev, st.Event
		}
	}
	timing := ""
	if fr.Converted > 0 && fr.MedianConvSecs > 0 {
		timing = fmt.Sprintf(" Median time to convert the full funnel: %s.", humanDuration(fr.MedianConvSecs))
	}
	return fmt.Sprintf("%d of %d users (%d%%) complete %s%s. The biggest drop-off is at \"%s\", %d users fall off there.%s",
		fr.Steps[len(fr.Steps)-1].Count, fr.Steps[0].Count, pct(fr.OverallConversion), ftitle, windowClause(win), worst, worstDrop, timing)
}

// humanDuration renders a time-to-convert like "45s", "12m", "3h 20m", or "2.5 days".
func humanDuration(secs float64) string {
	d := time.Duration(secs) * time.Second
	switch {
	case d < time.Minute:
		return fmt.Sprintf("%ds", int(d.Seconds()))
	case d < time.Hour:
		return fmt.Sprintf("%dm", int(d.Minutes()))
	case d < 24*time.Hour:
		h := int(d.Hours())
		if m := int(d.Minutes()) % 60; m != 0 {
			return fmt.Sprintf("%dh %dm", h, m)
		}
		return fmt.Sprintf("%dh", h)
	default:
		return fmt.Sprintf("%.1f days", d.Hours()/24)
	}
}

func answerRetention(evs []event.Event, vol []string, win askWindow, now time.Time, q string) string {
	// weekly/monthly/rolling asks take the bucketed path; the default daily path below is
	// kept byte-identical so nothing about the common case changes.
	if hasAny(q, "weekly", "week", "monthly", "month", "rolling", "unbounded") {
		return answerRetentionBucketed(evs, vol, win, now, q)
	}
	rr := retention.Compute(evs, 7, pickEvent(vol, "open"))
	// honest denominators: only cohorts old enough to observe day N (retention.DayN)
	d1, size1 := retention.DayN(rr, 1, now)
	if size1 == 0 {
		if win.scoped() {
			return "Not enough history " + win.label + " to measure retention, day-1 retention needs users past " +
				"their first day. Widen the window, or drop the time phrase for all history."
		}
		return "Not enough history yet to measure retention, check back once users are past their first day."
	}
	out := fmt.Sprintf("Day-1 retention is %d%% (of %d users past day 1).",
		int(float64(d1)/float64(size1)*100+0.5), size1)
	if d7, size7 := retention.DayN(rr, 7, now); size7 > 0 {
		out = fmt.Sprintf("Day-1 retention is %d%% and day-7 is %d%% (of %d and %d users old enough to measure).",
			int(float64(d1)/float64(size1)*100+0.5), int(float64(d7)/float64(size7)*100+0.5), size1, size7)
	}
	if win.scoped() {
		out += " Cohorts scoped to first activity " + win.label + "."
	}
	return out
}

// answerRetentionBucketed handles weekly/monthly/rolling retention asks: same honest
// denominator (only cohorts old enough to observe period N), reported in the unit asked for.
func answerRetentionBucketed(evs []event.Event, vol []string, win askWindow, now time.Time, q string) string {
	bucket, unit, p1, p2, maxP := "day", "day", 1, 7, 7
	if hasAny(q, "weekly", "week") {
		bucket, unit, p1, p2, maxP = "week", "week", 1, 4, 4
	}
	if hasAny(q, "monthly", "month") {
		bucket, unit, p1, p2, maxP = "month", "month", 1, 3, 3
	}
	rolling := hasAny(q, "rolling", "unbounded")
	rr := retention.ComputeBucketed(evs, maxP, pickEvent(vol, "open"), bucket, rolling)

	r1, s1 := retention.PeriodN(rr, p1, now)
	kind := unit
	if rolling {
		kind = "rolling " + unit
	}
	if s1 == 0 {
		return fmt.Sprintf("Not enough history yet to measure %s-over-%s retention, cohorts need to be past their first %s. Check back later, or drop the bucket for daily retention.", kind, unit, unit)
	}
	pctOf := func(a, b int) int { return int(float64(a)/float64(b)*100 + 0.5) }
	out := fmt.Sprintf("%s-1 retention is %d%% (of %d users past %s 1).", title(unit), pctOf(r1, s1), s1, unit)
	if r2, s2 := retention.PeriodN(rr, p2, now); s2 > 0 {
		out = fmt.Sprintf("%s-1 retention is %d%% and %s-%d is %d%% (of %d and %d users old enough to measure).",
			title(unit), pctOf(r1, s1), unit, p2, pctOf(r2, s2), s1, s2)
	}
	if rolling {
		out += " (Rolling: counts users active on that period or any later one.)"
	}
	if win.scoped() {
		out += " Cohorts scoped to first activity " + win.label + "."
	}
	return out
}

// title upper-cases the first letter (day -> Day) for the sentence-start unit label.
func title(s string) string {
	if s == "" {
		return s
	}
	return strings.ToUpper(s[:1]) + s[1:]
}

// answerChannels answers "which channel converts best" the way goal_report does:
// first-touch attribution per user, then per-source conversion to the site's
// conversion event, NOT the funnel, which ignores sources entirely.
func answerChannels(evs []event.Event, vol []string, win askWindow) string {
	if len(evs) == 0 {
		if win.scoped() {
			return "No events " + win.label + " to attribute, widen the window, or drop the time phrase for all history."
		}
		return "No events recorded yet."
	}
	srcProp := detectProp(evs, "source")
	if srcProp == "" {
		return "Your events don't carry any properties to attribute a channel from yet, send a " +
			"source/referrer/utm_source property with your events and ask again."
	}
	conv := pickConversion(evs, vol)

	// first-touch: a user's channel is srcProp on their FIRST event in the window
	firstTS := map[string]time.Time{}
	firstSrc := map[string]string{}
	converted := map[string]bool{}
	for _, e := range evs {
		if t, ok := firstTS[e.DistinctID]; !ok || e.Timestamp.Before(t) {
			firstTS[e.DistinctID] = e.Timestamp
			src, _ := e.Properties[srcProp].(string)
			if src == "" {
				src = "direct"
			}
			firstSrc[e.DistinctID] = src
		}
		if e.Name == conv {
			converted[e.DistinctID] = true
		}
	}
	type row struct {
		src              string
		users, converted int
	}
	bySrc := map[string]*row{}
	for id, src := range firstSrc {
		r := bySrc[src]
		if r == nil {
			r = &row{src: src}
			bySrc[src] = r
		}
		r.users++
		if converted[id] {
			r.converted++
		}
	}
	rows := make([]*row, 0, len(bySrc))
	for _, r := range bySrc {
		rows = append(rows, r)
	}
	// listing is volume-ordered (name breaks ties → deterministic run to run)
	sort.Slice(rows, func(i, j int) bool {
		if rows[i].users != rows[j].users {
			return rows[i].users > rows[j].users
		}
		return rows[i].src < rows[j].src
	})
	parts := []string{}
	for i, r := range rows {
		if i >= 3 {
			break
		}
		parts = append(parts, fmt.Sprintf("%s %d users → %d %s (%d%%)",
			r.src, r.users, r.converted, conv, int(float64(r.converted)/float64(r.users)*100+0.5)))
	}
	listing := fmt.Sprintf("By %s, first-touch%s: %s.", srcProp, windowClause(win), strings.Join(parts, ", "))
	if len(converted) == 0 {
		return listing + fmt.Sprintf(" No %q conversions in this data yet, so there is no honest \"best\" to rank.", conv)
	}
	// "best" = highest conversion rate; users break ties so a bigger sample wins
	best := rows[0]
	rate := func(r *row) float64 { return float64(r.converted) / float64(r.users) }
	for _, r := range rows[1:] {
		if rate(r) > rate(best) || (rate(r) == rate(best) && r.users > best.users) {
			best = r
		}
	}
	return fmt.Sprintf("%s converts best to \"%s\": %d of %d first-touch users (%d%%). %s",
		best.src, conv, best.converted, best.users, int(rate(best)*100+0.5), listing)
}

// pickConversion picks the event "converts" means for this dataset: the
// conventional conversion names when present, else the deepest step of the
// auto-detected journey funnel. The answer always names it, so the user sees
// exactly what was computed.
func pickConversion(evs []event.Event, vol []string) string {
	for _, want := range []string{"signup", "purchase", "checkout", "subscribe", "convert", "activate"} {
		if hasName(vol, want) {
			return want
		}
	}
	if steps, _ := detectFunnel(evs, vol); len(steps) > 0 {
		return steps[len(steps)-1].Event
	}
	return ""
}

func answerSignups(evs []event.Event, vol []string, win askWindow) string {
	ev := pickEvent(vol, "signup")
	if ev == "" {
		return "No events recorded yet."
	}
	tr := trends.Compute(evs, ev, win.from, win.to, false)
	days := len(tr.Points)
	if days == 0 {
		return "No events recorded yet."
	}
	if tr.Total == 0 && win.scoped() {
		return fmt.Sprintf("No \"%s\" events %s, widen the window, or drop the time phrase for all history.", ev, win.label)
	}
	if win.scoped() {
		return fmt.Sprintf("%d \"%s\" events %s, about %d/day.", tr.Total, ev, win.label, tr.Total/days)
	}
	return fmt.Sprintf("%d \"%s\" events over the last %d days, about %d/day.", tr.Total, ev, days, tr.Total/days)
}

func answerActive(evs []event.Event, win askWindow, now time.Time) string {
	if win.scoped() {
		users := distinctUsers(evs)
		if users == 0 {
			return "No active users " + win.label + ", widen the window, or drop the time phrase for all history."
		}
		return fmt.Sprintf("%d active users %s, across %d events.", users, win.label, len(evs))
	}
	total := distinctUsers(evs)
	cutoff := now.AddDate(0, 0, -7)
	recent := map[string]bool{}
	for _, e := range evs {
		if !e.Timestamp.Before(cutoff) { // inclusive "last 7 days", consistent with the engine
			recent[e.DistinctID] = true
		}
	}
	return fmt.Sprintf("%d total users, %d active in the last 7 days.", total, len(recent))
}

// answerEvent counts one named event over the window, the resolver for "how many
// checkout this week?" and the "your events" discovery chips. Mirrors answerSignups
// but for the exact event the user named rather than the picked default.
func answerEvent(evs []event.Event, ev string, win askWindow) string {
	tr := trends.Compute(evs, ev, win.from, win.to, false)
	days := len(tr.Points)
	if tr.Total == 0 {
		if win.scoped() {
			return fmt.Sprintf("No %q events %s. Widen the window, or drop the time phrase for all history.", ev, win.label)
		}
		return fmt.Sprintf("No %q events recorded yet.", ev)
	}
	per := tr.Total
	if days > 0 {
		per = tr.Total / days
	}
	if win.scoped() {
		return fmt.Sprintf("%d %q events %s, about %d/day.", tr.Total, ev, win.label, per)
	}
	return fmt.Sprintf("%d %q events over the last %d days, about %d/day.", tr.Total, ev, days, per)
}

// answerPage answers "visitors to /pricing" / "how many pageviews for /pqr" from
// autocaptured $pageview events. Path match is case- and trailing-slash-insensitive
// so the user never has to remember the exact casing.
func answerPage(evs []event.Event, path string, win askWindow) string {
	target := normPath(path)
	visitors := map[string]bool{}
	views := 0
	for _, e := range evs {
		if e.Name != "$pageview" {
			continue
		}
		p, _ := e.Properties["path"].(string)
		if normPath(p) != target {
			continue
		}
		views++
		if e.DistinctID != "" {
			visitors[e.DistinctID] = true
		}
	}
	if views == 0 {
		return fmt.Sprintf("No pageviews for %s%s. Double-check the path, or ask \"top pages\" to see what's tracked.", path, winSuffix(win))
	}
	return fmt.Sprintf("%s%s: %d visitors, %d pageviews.", path, winSuffix(win), len(visitors), views)
}

// answerWeb answers "how many pageviews / visitors / traffic" from autocaptured
// $pageview events — the fix for the router answering a signup count when the user
// asked about pageviews. Counts views and the distinct visitors behind them.
func answerWeb(evs []event.Event, win askWindow) string {
	visitors := map[string]bool{}
	views := 0
	for _, e := range evs {
		if e.Name != "$pageview" {
			continue
		}
		views++
		if e.DistinctID != "" {
			visitors[e.DistinctID] = true
		}
	}
	if views == 0 {
		if win.scoped() {
			return "No pageviews " + win.label + ". The browser snippet autocaptures $pageview events — widen the window, or drop the time phrase for all history."
		}
		return "No pageviews recorded yet. The browser snippet autocaptures $pageview events — check it's installed on your site."
	}
	return fmt.Sprintf("%d pageviews from %d visitors%s.", views, len(visitors), winSuffix(win))
}

// answerTopPages ranks the most-viewed paths from $pageview events — the answer for
// "top pages" / "most visited", which used to deflect to the capabilities menu.
func answerTopPages(evs []event.Event, win askWindow) string {
	views := map[string]int{}
	for _, e := range evs {
		if e.Name != "$pageview" {
			continue
		}
		p, _ := e.Properties["path"].(string)
		if p == "" {
			p = "(no path)"
		}
		views[normPath(p)]++
	}
	if len(views) == 0 {
		if win.scoped() {
			return "No pageviews " + win.label + " to rank. Widen the window, or drop the time phrase for all history."
		}
		return "No pageviews recorded yet to rank. The browser snippet autocaptures $pageview events."
	}
	type pageRow struct {
		path string
		n    int
	}
	rows := make([]pageRow, 0, len(views))
	for p, n := range views {
		rows = append(rows, pageRow{p, n})
	}
	sort.Slice(rows, func(i, j int) bool {
		if rows[i].n != rows[j].n {
			return rows[i].n > rows[j].n
		}
		return rows[i].path < rows[j].path
	})
	parts := []string{}
	for i, r := range rows {
		if i >= 5 {
			break
		}
		parts = append(parts, fmt.Sprintf("%s (%d)", r.path, r.n))
	}
	return fmt.Sprintf("Top pages by pageviews%s: %s.", winSuffix(win), strings.Join(parts, ", "))
}

// extractPath pulls a URL path token ("/pricing") out of a question, so "visitors to
// /pricing?" resolves to /pricing. Returns "" when no path is mentioned.
func extractPath(q string) string {
	for _, w := range strings.Fields(q) {
		if strings.HasPrefix(w, "/") && len(w) > 1 {
			return strings.TrimRight(w, "?.,!\"')")
		}
	}
	return ""
}

// normPath lower-cases and strips a trailing slash so "/Pricing" and "/pricing/"
// both match the stored "/pricing".
func normPath(p string) string {
	p = strings.ToLower(strings.TrimSpace(p))
	if len(p) > 1 {
		p = strings.TrimRight(p, "/")
	}
	return p
}

// namedEvent returns the first (highest-volume) real event name the question mentions
// as a whole token. Skips $-prefixed internal events (those are pages, handled by path).
func namedEvent(q string, vol []string) string {
	toks := map[string]bool{}
	for _, w := range strings.Fields(q) {
		toks[strings.Trim(w, "?.,!\"'()")] = true
	}
	for _, ev := range vol {
		if strings.HasPrefix(ev, "$") {
			continue
		}
		if toks[strings.ToLower(ev)] {
			return ev
		}
	}
	return ""
}

// unknownNamedEvent returns an event-shaped token the user explicitly asked about
// ("the flibbergibbet event", "how many zorptastic events fired") that is NOT in the
// dataset — so the caller can answer honestly instead of substituting a default event.
// It only fires on the explicit "<token> event(s)" pattern to avoid bouncing generic
// asks ("how many signups"): the word "event"/"events" must sit next to the token, and
// the token must not itself be a known event (that case is answerEvent's) or a generic
// metric/filler word.
func unknownNamedEvent(q string, vol []string) string {
	known := map[string]bool{}
	for _, ev := range vol {
		known[strings.ToLower(ev)] = true
	}
	words := strings.Fields(q)
	for i, w := range words {
		bare := strings.ToLower(strings.Trim(w, "?.,!\"'()"))
		if bare != "event" && bare != "events" {
			continue
		}
		// the candidate is the neighbouring noun: "the X event" (before) or
		// "X events fire" (also before). Fall back to the word after when the word
		// before is filler ("the", "an").
		var cand string
		if i > 0 {
			cand = strings.ToLower(strings.Trim(words[i-1], "?.,!\"'()"))
		}
		if (cand == "" || isFillerWord(cand)) && i+1 < len(words) {
			cand = strings.ToLower(strings.Trim(words[i+1], "?.,!\"'()"))
		}
		if cand == "" || isFillerWord(cand) || known[cand] || cand == "event" || cand == "events" {
			continue
		}
		return cand
	}
	return ""
}

// isFillerWord skips articles/generic nouns so "the ... event" resolves to the real
// name token, not to "the" or "many".
func isFillerWord(w string) bool {
	switch w {
	case "the", "a", "an", "any", "each", "this", "that", "my", "your", "which",
		"what", "how", "many", "much", "number", "count", "total", "of", "did",
		"does", "do", "fire", "fired", "fires", "named", "called", "custom":
		return true
	}
	return false
}

// answerUnknownEvent tells the user the named event doesn't exist and points at the
// nearest real name (and the discovery chips) rather than answering a substitute.
func answerUnknownEvent(name string, vol []string) string {
	real := make([]string, 0, len(vol))
	for _, ev := range vol {
		if !strings.HasPrefix(ev, "$") {
			real = append(real, ev)
		}
	}
	if len(real) == 0 {
		return fmt.Sprintf("No event named %q — in fact no product events are recorded yet. Send some with track(), then ask again.", name)
	}
	if near := nearestEvent(name, real); near != "" {
		return fmt.Sprintf("No event named %q. Did you mean %q? Your tracked events: %s.", name, near, strings.Join(cap8(real), ", "))
	}
	return fmt.Sprintf("No event named %q. Your tracked events: %s. Ask about one of those.", name, strings.Join(cap8(real), ", "))
}

// cap8 trims a listing to eight names so the answer stays one line.
func cap8(names []string) []string {
	if len(names) > 8 {
		return names[:8]
	}
	return names
}

// nearestEvent returns the closest real event name to the mistyped one by edit
// distance, but only when it's a plausible typo (distance ≤ 40% of the name) — a
// wild miss ("flibbergibbet") gets no misleading suggestion.
func nearestEvent(name string, real []string) string {
	best, bestD := "", 1<<30
	for _, ev := range real {
		d := levenshtein(name, strings.ToLower(ev))
		if d < bestD {
			best, bestD = ev, d
		}
	}
	if best == "" {
		return ""
	}
	limit := len(name) * 2 / 5
	if limit < 1 {
		limit = 1
	}
	if bestD <= limit {
		return best
	}
	return ""
}

// levenshtein is the standard edit distance, small strings only (event names), so a
// simple two-row DP is plenty.
func levenshtein(a, b string) int {
	ra, rb := []rune(a), []rune(b)
	prev := make([]int, len(rb)+1)
	cur := make([]int, len(rb)+1)
	for j := range prev {
		prev[j] = j
	}
	for i := 1; i <= len(ra); i++ {
		cur[0] = i
		for j := 1; j <= len(rb); j++ {
			cost := 1
			if ra[i-1] == rb[j-1] {
				cost = 0
			}
			cur[j] = min3(cur[j-1]+1, prev[j]+1, prev[j-1]+cost)
		}
		prev, cur = cur, prev
	}
	return prev[len(rb)]
}

func min3(a, b, c int) int {
	if b < a {
		a = b
	}
	if c < a {
		a = c
	}
	return a
}

// countish reports whether the question is asking for a count/volume, so a bare
// event mention ("how is checkout doing") still falls through to the funnel intent.
func countish(q string) bool {
	return hasAny(q, "how many", "how much", "count", "number of", "total", "mau", "dau", "wau",
		"monthly active", "daily active", "weekly active")
}

// winSuffix renders " <label>" for a scoped window, "" otherwise.
func winSuffix(w askWindow) string {
	if w.scoped() && w.label != "" {
		return " " + w.label
	}
	return ""
}

func hasAny(s string, subs ...string) bool {
	for _, sub := range subs {
		if strings.Contains(s, sub) {
			return true
		}
	}
	return false
}

// answerGeo counts distinct visitor countries (ingest-time geo). Geo stamping
// began when the operator's instance first ran a geo-enabled build and IPs are
// never stored, so history before that carries no country — the answer SAYS so
// whenever the asked window predates the first stamped event, instead of letting
// an honest small number read as a broken one.
func answerGeo(scoped, all []event.Event, win askWindow) string {
	type cAgg struct {
		visitors map[string]bool
		views    int
	}
	byCC := map[string]*cAgg{}
	for _, e := range scoped {
		if e.Name != "$pageview" {
			continue
		}
		cc, _ := e.Properties["country"].(string)
		if cc == "" {
			continue
		}
		a := byCC[cc]
		if a == nil {
			a = &cAgg{visitors: map[string]bool{}}
			byCC[cc] = a
		}
		a.views++
		a.visitors[e.DistinctID] = true
	}
	// the honesty clause: when did geo stamping actually begin on this instance?
	var firstGeo time.Time
	for _, e := range all {
		if _, ok := e.Properties["country"].(string); ok {
			if firstGeo.IsZero() || e.Timestamp.Before(firstGeo) {
				firstGeo = e.Timestamp
			}
		}
	}
	note := ""
	if !firstGeo.IsZero() && (!win.scoped() || win.from.Before(firstGeo)) {
		note = " Geo stamping began " + firstGeo.Format("Jan 2") + " on this instance (the IP is used for one lookup at ingest and never stored), so earlier events carry no country."
	}
	if len(byCC) == 0 {
		if firstGeo.IsZero() {
			return "No country data yet. Geo stamps at ingest from the free DB-IP database, so countries appear as new visitors arrive (IPs are never stored). If this instance runs with SMOLANALYTICS_GEO=off, that is why."
		}
		if win.scoped() {
			return "No geo-stamped pageviews " + win.label + "." + note
		}
		return "No geo-stamped pageviews yet." + note
	}
	type row struct {
		cc       string
		visitors int
	}
	rows := make([]row, 0, len(byCC))
	for cc, a := range byCC {
		rows = append(rows, row{cc, len(a.visitors)})
	}
	sort.Slice(rows, func(i, j int) bool { return rows[i].visitors > rows[j].visitors })
	parts := make([]string, 0, 5)
	for i, r := range rows {
		if i == 5 {
			break
		}
		parts = append(parts, fmt.Sprintf("%s (%d)", r.cc, r.visitors))
	}
	scope := "across all recorded geo data"
	if win.scoped() {
		scope = win.label
	}
	more := ""
	if len(rows) > 5 {
		more = fmt.Sprintf(" and %d more", len(rows)-5)
	}
	noun := "countries"
	if len(rows) == 1 {
		noun = "country"
	}
	return fmt.Sprintf("Visitors came from %d %s %s: %s%s.%s", len(rows), noun, scope, strings.Join(parts, ", "), more, note)
}
