package api

import (
	"encoding/json"
	"fmt"
	"io"
	"math"
	"net/http"
	"regexp"
	"sort"
	"strconv"
	"strings"
	"time"

	"github.com/Arjun0606/smolanalytics/internal/brief"
	"github.com/Arjun0606/smolanalytics/internal/event"
	"github.com/Arjun0606/smolanalytics/internal/funnel"
	"github.com/Arjun0606/smolanalytics/internal/query"
	"github.com/Arjun0606/smolanalytics/internal/retention"
	"github.com/Arjun0606/smolanalytics/internal/trends"
)

// ask answers a plain-English question about the data with zero dependencies,
// it routes common questions (conversion, retention, signups, channels, active
// users, the weekly brief) deterministically, right in the dashboard, no model
// required. For arbitrary questions the user connects smolanalytics to their
// OWN Claude / Cursor over MCP (we never call a model ourselves), see internal/mcp.
func (s *Server) ask(w http.ResponseWriter, r *http.Request) {
	body, _ := io.ReadAll(io.LimitReader(r.Body, 1<<20))
	var req struct {
		Question string `json:"question"`
	}
	_ = json.Unmarshal(body, &req)
	q := strings.ToLower(strings.TrimSpace(req.Question))
	if q == "" {
		writeErr(w, http.StatusBadRequest, "ask a question")
		return
	}
	evs, err := s.store.Range(time.Time{}, time.Time{})
	if err != nil {
		writeErr(w, http.StatusInternalServerError, err.Error())
		return
	}
	evs = query.Apply(evs, nil) // production scope: dev-env events excluded by default

	now := time.Now().UTC()
	// every answer ships with its receipt: which deterministic report produced it, over
	// what window, and the guarantee that a CI test proves it can't be fabricated. "Plain
	// English analytics" makes people fear hallucinated numbers — show the work so they can
	// verify before they trust. The intent is the deterministic route the classifier picked,
	// exposed so a UI can render the matching chart under the answer (reports-as-answers)
	// without re-classifying the question and drifting from the engine.
	// a refusal (unsupported time window) must return NO intent: the UIs chart by
	// intent, and a chart under "I can't answer that" reads as an answer anyway —
	// the exact incoherence the proof chip exists to prevent.
	intent := string(classifyAsk(q))
	if _, unsupported := parseWindow(q, now); unsupported != "" {
		intent = "" // a refused window renders no chart (would sit under "I can't answer")
	}
	// a question that resolved to a SPECIFIC named event (e.g. "purchases" -> checkout)
	// must not chart the classified intent's default series — better no chart than a
	// signups line under a checkout answer. webdim/live/geo are list answers with no
	// trend chart, so they render nothing anyway.
	if ev := namedEvent(q, eventsByVolume(query.Apply(evs, nil))); ev != "" && countish(q) {
		intent = ""
	}
	writeJSON(w, http.StatusOK, map[string]string{
		"answer":      answer(q, evs, now),
		"computed_by": computedBy(q, evs, now),
		"intent":      intent,
	})
}

// computedBy is the "show your work" receipt for an answer: the exact deterministic
// report + scope behind it, plus the trust guarantee. Read-only, so a founder can sanity
// check the method before trusting the number.
func computedBy(q string, evs []event.Event, now time.Time) string {
	if isAction(q) {
		return "" // action asks aren't data answers
	}
	win, _ := parseWindow(q, now)
	scope := "all recorded events"
	if win.scoped() && win.label != "" {
		scope = strings.TrimSpace(win.label)
	}
	receipt := func(report string) string {
		return "Computed by " + report + " over " + scope + ", the same engine the dashboard runs, not generated by a model. A CI test asserts this number equals the dashboard's report, so it cannot be fabricated. Open that report on the dashboard to verify."
	}
	intent := classifyAsk(q)
	// The segment / period-comparison layer (ask_scope.go) intercepts a question REGARDLESS
	// of the coarse intent — "how is reddit doing?" answers as a segment, not the verdict.
	// The receipt must describe the route ACTUALLY taken, or it names a different report than
	// the one that produced the number (a self-contradiction the receipt exists to prevent).
	// Mirror answer()'s precedence: measure and explicit-trend win before the segment layer.
	if _, _, cok := parseCompare(q, now); cok {
		return receipt("the period-comparison report (the same metric across two windows)")
	}
	// mirror answer()'s pre-intent "break down <event> by <property>" branch — without this
	// the receipt re-classified the question as unknown and told the user "no matching
	// event... I showed the weekly pulse instead" directly under a correct breakdown answer.
	if intent != intentConvBy && intent != intentRetention && intent != intentFunnel &&
		intent != intentMeasure && intent != intentPaths && intent != intentLifecycle &&
		intent != intentStickiness && intent != intentEngagement {
		if prop := breakdownByProp(q, evs); prop != "" {
			if ev := namedEvent(normalizeEventWords(q), eventsByVolume(evs)); ev != "" {
				for _, e := range evs {
					if e.Name == ev {
						if _, ok := e.Properties[prop]; ok {
							return receipt(fmt.Sprintf("the property-breakdown report (%q events per %q value)", ev, prop))
						}
					}
				}
			}
		}
	}
	if intent != intentMeasure && intent != intentConvBy && intent != intentSplit &&
		!hasAny(q, "trend", "over time", "trajectory") {
		if segs := extractSegments(q, evs); len(segs) >= 1 {
			if len(segs) >= 2 {
				return receipt("the segment-vs-segment report (each named segment, first-touch attributed)")
			}
			switch intent {
			case intentGeo, intentWebDim, intentFunnel, intentRetention, intentEngagement,
				intentHours, intentTopPages, intentEntryPages, intentAI, intentPeakDay,
				intentStickiness, intentLifecycle:
				// the segment merely FILTERS a breakdown report — the intent switch below
				// already describes it; only note the scoping.
				return receipt(reportForIntent(intent) + " (scoped to the named segment, first-touch attributed)")
			default:
				return receipt("the segment report (the named segment vs the rest, first-touch attributed)")
			}
		}
	}
	if intent == intentUnknown {
		return "You asked about something with no matching event, so nothing was fabricated. I showed the weekly pulse instead, computed deterministically. Send that metric as an event and I'll report it."
	}
	return receipt(reportForIntent(intent))
}

// reportForIntent names the deterministic report behind each intent, for the receipt.
func reportForIntent(intent askIntent) string {
	var report string
	switch intent {
	case intentBrief:
		report = "the verdict engine (notable-change detection + the weekly pulse)"
	case intentFunnel:
		report = "the funnel report"
	case intentChannels:
		report = "the first-touch channel-attribution report"
	case intentRetention:
		report = "the retention report"
	case intentActive:
		report = "the active-users report"
	case intentSignups:
		report = "the event-trend report"
	case intentWeb:
		report = "the web-overview report"
	case intentTopPages:
		report = "the top-pages report"
	case intentGeo:
		report = "the geo (countries) breakdown of the web-overview report"
	case intentEngagement:
		report = "the engagement report (visible+focused time measured by the SDK)"
	case intentMeasure:
		report = "the numeric-aggregation report (a deterministic sum/avg/median/p90 over a property you sent)"
	case intentSources:
		report = "the traffic-by-source ranking (referrer breakdown of the web-overview report, direct included)"
	case intentStickiness:
		report = "the stickiness report (DAU/MAU over exact distinct users)"
	case intentPaths:
		report = "the paths (user-journey) report — the ranked next events after the anchor"
	case intentLifecycle:
		report = "the lifecycle report (new vs returning vs dormant, exact distinct users)"
	case intentHours:
		report = "the activity-by-hour histogram"
	case intentEntryPages:
		report = "the entry-pages report (each user's first pageview in the window)"
	case intentPeakDay:
		report = "the daily event-trend report (peak bucket)"
	case intentSplit:
		report = "the referrer/utm split of the web-overview report"
	case intentAI:
		report = "the AI-referrers breakdown of the web-overview report"
	case intentConvBy:
		report = "the conversion-by-segment report (distinct users per bucket)"
	default:
		report = "a deterministic report"
	}
	return report
}

// askIntent is the deterministic route the ask bar picked for a question, a
// named type (not bare strings) so the router and its tests cannot drift apart.
type askIntent string

const (
	intentAction     askIntent = "action"
	intentBrief      askIntent = "brief"
	intentRetention  askIntent = "retention"
	intentChannels   askIntent = "channels"
	intentGeo        askIntent = "geo"
	intentWebDim     askIntent = "webdim"
	intentEngagement askIntent = "engagement"
	intentLive       askIntent = "live"
	intentTopPages   askIntent = "toppages"
	intentWeb        askIntent = "web"
	intentFunnel     askIntent = "funnel"
	intentActive     askIntent = "active"
	intentSignups    askIntent = "signups"
	intentMeasure    askIntent = "measure"
	intentSources    askIntent = "sources"
	intentStickiness askIntent = "stickiness"
	intentLifecycle  askIntent = "lifecycle"
	intentPaths      askIntent = "paths"
	intentHours      askIntent = "hours"
	intentEntryPages askIntent = "entrypages"
	intentPeakDay    askIntent = "peakday"
	intentSplit      askIntent = "split"
	intentAI         askIntent = "ai"
	intentConvBy     askIntent = "convby"
	intentUnknown    askIntent = "unknown"
)

// classifyAsk routes a lowercased question to one intent. Order is the whole
// game: action-y asks must never fall through to a metric ("alert me if signups
// drop" mentions both), and specific phrasings outrank generic keywords,
// "which channel converts best" is a channel question, not a funnel one, and
// "how many active users" is a user count, not a signup trend.
func classifyAsk(q string) askIntent {
	switch {
	case isAction(q):
		return intentAction
	// "what should I fix" is the product's own tagline — it, and every health-check
	// phrasing, must land on the verdict, never the capabilities menu.
	case hasAny(q, "how are things", "how's it going", "how is it going", "what happened",
		"weekly report", "week in review", "summary", "overview", "digest", "brief",
		"what should i fix", "what to fix", "needs fixing", "fix first", "broken",
		"what's wrong", "whats wrong", "going wrong", "wrong with", "problem",
		"needs attention", "what should i do", "priorit", "red flag", "biggest issue",
		"why did", "why are", "why is"):
		return intentBrief
	// numeric aggregation (revenue = sum of amount, AOV = avg, p90 latency) BEFORE the
	// count-y intents, so "total revenue"/"average order value" aren't answered as a
	// checkout count. Resolves to a real number only if the property was actually sent.
	case isMeasureAsk(q):
		return intentMeasure
	// splits and rankings that would otherwise fall into channels or refuse
	case hasAny(q, "direct vs search", "search vs direct", "paid vs organic", "organic vs paid"):
		return intentSplit
	case hasAny(q, "ai tools", "ai assistants", "ai referrers", "from ai", "llm traffic"):
		return intentAI
	case hasAny(q, "land on", "landing page", "entry page", "enter the site", "enter on"):
		return intentEntryPages
	case hasAny(q, "best day", "biggest day", "peak day", "busiest day", "biggest traffic day", "worst day",
		"slowest day", "which day", "what day"):
		return intentPeakDay
	case hasAny(q, "when are users most active", "when are people most active", "what hour", "which hour",
		"busiest hour", "busiest time", "peak hour", "time of day", "hour of the day", "hour of day"):
		return intentHours
	case hasAny(q, "what do users do after", "what do people do after", "what happens after",
		"do next", "do after they", "what do they do next", "user journey", "user journeys", "pathfinder"):
		return intentPaths
	case hasAny(q, "stickiness", "sticky", "dau over mau", "dau/mau", "dau to mau"):
		return intentStickiness
	case hasAny(q, "churn", "dormant", "went quiet", "stopped coming", "stopped using",
		"new or returning", "new vs returning", "returning vs new", "returning users", "returning visitors"):
		return intentLifecycle
	// conversion by a segment dimension ("which browser converts best") — before
	// retention/channels/funnel so the dimension wins the route
	case hasAny(q, "convert", "conversion", "converts") && hasAny(q, "by country", "by device", "by browser",
		"by os", "by plan", "by source", "which country", "which browser", "which device", "which os",
		"country has the best", "browser converts", "device converts", "mobile or desktop users convert",
		"desktop or mobile users convert"):
		return intentConvBy
	case hasAny(q, "retention", "retain", "come back", "comeback", "coming back", "came back", "stick around", "sticking around"):
		return intentRetention
	// top-pages must outrank both channels ("which pages" ≠ "which sources") and the
	// web-volume case below.
	case hasAny(q, "top page", "top pages", "most visited", "popular page", "most viewed",
		"which page", "best page", "top url", "top path", "top content"):
		return intentTopPages
	// geo = country questions. Before channels so "how many countries" and "which
	// countries" never land on sources or a signup trend.
	case hasAny(q, "countr", "geograph", "which nations", "around the world", "worldwide",
		"where are my users", "where are our users", "where are users from", "where our users are"):
		return intentGeo
	// sources = the traffic RANKING (referrers by visitors, direct included). channels =
	// first-touch conversion attribution — only when the question is about converting.
	case hasAny(q, "where is our traffic coming from", "where is traffic coming from", "where does our traffic come from",
		"top referrer", "top referrers", "referrers", "how are folks finding", "how are people finding",
		"how do people find", "where do people find"):
		return intentSources
	case hasAny(q, "channel", "source", "acquisition", "referr", "utm", "campaign",
		"come from", "coming from", "came from", "where do my", "where are my visitors"):
		if hasAny(q, "convert", "conversion", "drives the most", "drive the most", "signup", "sign up", "best channel") {
			return intentChannels
		}
		return intentSources
	// who's here now — the live count, before the generic web case
	case hasAny(q, "right now", "on the site now", "online now", "live visitor", "who's on",
		"whos on", "active right now", "currently on", "here now", " rn", "anyone live"):
		if hasAny(q, "last hour", "past hour", "last 6 hours", "hours") {
			return intentWeb // a windowed count, not the live-now feed
		}
		return intentLive
	case hasAny(q, "anyone on the site", "anybody on the site", "anyone visit"):
		return intentWeb
	// engagement questions answer from $engagement (visible+focused time the SDK
	// measures) — before webdim so they never bounce to the capabilities menu
	case hasAny(q, "engagement", "engaged", "time on site", "time on page", "session duration",
		"session time", "how long do people stay", "how long do users stay", "how long do folks",
		"actually stay", "stay on the site", "dwell"):
		return intentEngagement
	// standard web dimensions the dashboard shows (device/browser/os/bounce) — before
	// the web-volume case so "what devices" isn't answered as a pageview count
	case hasAny(q, "device", "mobile vs desktop", "browser", "operating system", " os ",
		"bounce", "bounce rate"):
		return intentWebDim
	// web volume = pageviews / visitors / traffic counts. After channels so "where do
	// visitors come from" stays a channel question, but BEFORE signups so "how many
	// pageviews" is never answered as a signup count (the confidently-wrong bug).
	case hasAny(q, "pageview", "page view", "traffic", "visits", "visit", "visited", "visitor",
		"unique visitor", "how many views", "people came", "folks came", "people landed"):
		if hasAny(q, "convert", "conversion") {
			return intentFunnel // "does traffic from reddit actually convert"
		}
		return intentWeb
	case hasAny(q, "convert", "conversion", "funnel", "drop", "checkout", "check out", "checking out",
		"activat", "end up", "go on to"):
		return intentFunnel
	case hasAny(q, "active", "dau", "wau", "mau", "total users", "how many users", "user count",
		"used the product", "using the product", "used the app", "used the site"):
		return intentActive
	case hasAny(q, "signup", "sign up", "sign-up", "new user", "growth", "trend", "how many"):
		return intentSignups
	default:
		return intentUnknown
	}
}

// isAction spots asks that want to CHANGE something. The ask bar is read-only,
// these must never come back as a metric that pretends the change happened.
func isAction(q string) bool {
	if hasAny(q, "alert", "notify", "rename", "configure", "turn on", "turn off",
		"retention to", "set retention", "change retention") {
		return true
	}
	for _, verb := range []string{"set ", "change ", "enable ", "disable ", "delete ",
		"create ", "add ", "save ", "update ", "remove "} {
		if strings.HasPrefix(q, verb) {
			return true
		}
	}
	return false
}

func answer(q string, evs []event.Event, now time.Time) string {
	intent := classifyAsk(q)
	switch intent {
	case intentAction:
		return answerAction(q)
	case intentBrief:
		// P2-6: a "why are people leaving / churning" question can't be answered
		// directly (there's no reason attached to an absence). Say so honestly, then
		// offer the closest real read (retention + drop-off) rather than jumping
		// silently into the weekly pulse as if it answered the "why".
		if hasAny(q, "why are people leav", "why do people leav", "why are users leav",
			"why are people churn", "why do people churn", "why are we losing", "why do we lose",
			"why are people droppi", "why do people droppi") {
			return "I can't tell you WHY people leave — that's a judgment call no metric holds. " +
				"What I can show is WHERE they drop and whether they come back, which is usually where the answer starts:\n\n" +
				answerBrief(evs, briefDays(q), now)
		}
		return answerBrief(evs, briefDays(q), now)
	}

	win, unsupported := parseWindow(q, now)
	if unsupported != "" {
		// the window shapes parseWindow can't do (since monday, june 20 – june 30)
		if xw, ok := parseExtraWindow(q, now); ok {
			win, unsupported = xw, ""
		}
	}
	// a two-period comparison carries its own windows ("week over week pageviews"),
	// so the unsupported-window refusal must not fire ahead of it
	curW, priorW, cok := parseCompare(q, now)
	// intents whose vocabulary contains day/week/month/hour AS THE METRIC ("week 1
	// retention", "peak hour") must not bounce off the window parser
	if unsupported != "" && !cok && !windowTolerantIntent(intent) {
		return fmt.Sprintf("I can't scope to %q from the ask bar, supported windows: today, yesterday, "+
			"this/last week, this/last month, \"last N days\", \"last N hours\", \"since monday\", and "+
			"\"between jun 20 and jun 30\". Re-ask with one of those, or drop the "+
			"time phrase for all recorded history. For arbitrary ranges, ask your agent over MCP, the "+
			"trends and funnel tools take exact dates.", unsupported)
	}
	volAll := eventsByVolume(evs) // event NAMES come from the full schema, metrics from the window
	scoped := scope(evs, win)

	// "break down <event> by <property>" / "<event> by <property>" over a NAMED event and one
	// of ITS OWN properties (signups by plan, checkout by tier). Without this, "break down
	// signup by device" bounced to the web user-agent dimension ("No devices recorded") and
	// "signups by plan" dropped the dimension and returned the flat aggregate. Guarded so it
	// never steals conversion/retention/funnel questions that own the "by <dim>" phrasing.
	if intent != intentConvBy && intent != intentRetention && intent != intentFunnel &&
		intent != intentMeasure && intent != intentPaths && intent != intentLifecycle &&
		intent != intentStickiness && intent != intentEngagement {
		if prop := breakdownByProp(q, evs); prop != "" {
			if ev := namedEvent(normalizeEventWords(q), volAll); ev != "" {
				pool := make([]event.Event, 0, len(evs))
				carries := false
				for _, e := range evs {
					if e.Name == ev {
						pool = append(pool, e)
						if _, ok := e.Properties[prop]; ok {
							carries = true
						}
					}
				}
				if carries {
					// "how many USERS signed up by plan" wants distinct users; the default
					// ("break signups down by plan") wants EVENT counts (matching GET /v1/breakdown).
					if hasAny(q, "how many users", "how many people", "unique user", "distinct user",
						"unique people", "users signed", "users did", "people did", "by user") {
						return answerPropBreakdownLabel(pool, prop, "users", win)
					}
					return answerPropBreakdownEvents(pool, prop, ev+"s", win)
				}
			}
		}
	}

	// Numeric aggregation wins before the path/event-name shortcuts, so "average order
	// value" isn't hijacked into a checkout COUNT by the named-event branch below.
	if intent == intentMeasure {
		// pass the FULL event set (not the window-scoped one): answerMeasure discovers the
		// named segment's value from the data, and a value that only occurs OUTSIDE the window
		// (e.g. "free users" whose events predate "today") must still resolve — the window is
		// re-applied inside ComputeMeasure. Scoping first would silently drop the segment.
		return answerMeasure(evs, q, volAll, win)
	}
	// paths must dispatch before the named-event branch below, or "what do users do after
	// signup" gets hijacked into a signup COUNT instead of the journey.
	if intent == intentPaths {
		return answerPaths(evs, q, volAll, win)
	}

	// The comparison and segment layer (ask_scope.go): "this week vs last week",
	// "traffic from reddit", "android vs ios signups" — the three question shapes the
	// ask battery failed hardest on. Runs before the named-event shortcut so
	// "checkouts this week vs last week" compares instead of counting one window.
	qe := normalizeEventWords(q)
	segs := extractSegments(q, evs)
	m := resolveMetric(qe, volAll)
	if cok {
		if intent == intentFunnel && (m.kind == "visitors" || hasAny(q, "rate", "conversion", "convert")) {
			return answerCompareFunnel(evs, volAll, q, curW, priorW)
		}
		cmpSegs := segs
		if len(cmpSegs) == 0 {
			if p := extractPath(q); p != "" {
				cmpSegs = []askSeg{{prop: "path", value: p, label: p, found: true}}
			}
		}
		return answerCompareWindows(evs, m, cmpSegs, curW, priorW)
	}
	// "how does our conversion compare to industry benchmarks" — we have no benchmark
	// data and must say so before showing the real funnel
	if hasAny(q, "benchmark", "industry average", "industry standard") {
		return "I only compute from your own events — there's no industry-benchmark data here, and I won't invent one. Your funnel, exactly: " +
			answerFunnel(scoped, volAll, win, q)
	}
	// "what share of visitors ever sign up" — the event-per-visitor rate
	if hasAny(q, "share of visitors", "percent of visitors", "% of visitors", "fraction of visitors") {
		if ev := namedEvent(qe, volAll); ev != "" {
			return answerVisitorShare(scoped, ev, win)
		}
	}
	// P2-7: "signup conversion rate" / "what % of visitors sign up" most likely means
	// visitor→signup, not the post-signup funnel. Lead with that rate (and point at the
	// funnel for the deeper cut) instead of answering a different question.
	if hasAny(q, "signup conversion", "sign up conversion", "signup rate", "sign-up rate",
		"visitor to signup", "visitors sign up", "visitors who sign up") {
		if ev := pickEvent(volAll, "signup"); ev != "" {
			return answerVisitorShare(scoped, ev, win) +
				" (That's visitor→" + ev + "; ask \"where do people drop off\" for the full funnel after that.)"
		}
	}
	// "social traffic trend over the last 30 days" wants a SERIES, not one scalar
	if hasAny(q, "trend", "over time", "trajectory") && (len(segs) == 1 || m.kind == "event") {
		return answerTrendText(evs, m, segs, win, now)
	}
	if intent != intentConvBy && intent != intentSplit {
		if len(segs) == 2 {
			if intent == intentRetention {
				return answerRetentionVsSeg(evs, win, now, q, segs[0], segs[1])
			}
			// "pro vs free CONVERSION RATE" is a RATE comparison, not a raw-count one — comparing
			// signup counts ("free leads, 30 vs 25") gives the OPPOSITE of the truth when free has
			// more signups but converts worse. Route same-property conversion questions to the
			// per-segment funnel so it compares rates, with a sample floor.
			if segs[0].prop == segs[1].prop && hasAny(q, "conversion", "convert", "rate") {
				if fs := detectFunnelForConv(evs, volAll, q); len(fs) >= 2 {
					return answerConvBySteps(scope(evs, win), segs[0].prop, fs, win)
				}
			}
			// two segments on DIFFERENT properties with no comparison word mean an AND filter
			// ("pro signups on desktop" = plan=pro AND device=desktop), not "X vs Y". Answering
			// it as a comparison (or dropping one) returns a wrong number as fact.
			if segs[0].prop != segs[1].prop && !hasAny(q, " vs ", "versus", "compared to", " or ", " against ") {
				return answerSegAnd(evs, m, segs[0], segs[1], win)
			}
			return answerSegVsSeg(evs, m, segs[0], segs[1], win)
		}
		if len(segs) == 1 {
			switch intent {
			case intentGeo, intentWebDim, intentFunnel, intentRetention, intentEngagement, intentHours, intentTopPages, intentEntryPages, intentAI, intentPeakDay, intentStickiness, intentLifecycle:
				// the segment FILTERS a breakdown-style report ("retention for mobile
				// users", "which countries does our twitter traffic come from").
				// user-journey reports scope by USER — a reddit visitor's signup event
				// doesn't carry the referrer property.
				if !segs[0].found {
					return fmt.Sprintf("0 — no events with %s = %s have been sent, so there's nothing to report for %s.", segs[0].prop, segs[0].label, segs[0].label)
				}
				if intent == intentFunnel || intent == intentRetention || intent == intentEngagement || intent == intentStickiness || intent == intentLifecycle {
					evs = segFilterUsers(evs, segs[0])
				} else {
					evs = segFilter(evs, segs[0])
				}
				scoped = scope(evs, win)
				segNote := " (scoped to " + segs[0].label + ")"
				return answerScopedIntent(intent, evs, scoped, volAll, win, now, q) + segNote
			default:
				return answerSegment(evs, m, segs[0], win)
			}
		}
	}

	// Explicit page-path or event-name mentions answer about exactly what the user named,
	// taking priority over the generic intents. This is what lets the "your pages" and
	// "your events" discovery chips resolve to a real answer instead of a generic one, and
	// what makes "visitors to /pricing" and "how many checkout this week" just work.
	if path := extractPath(q); path != "" {
		return answerPage(scoped, path, win)
	}
	// "how many events did we receive all time" / "total event volume" — the count of ALL
	// events, not any single event. Without this it fell to namedEvent()'s default and
	// reported one event's count (e.g. signup=7) as the grand total (2,258).
	if isTotalEventsAsk(q, volAll) {
		users := map[string]bool{}
		for _, e := range scoped {
			users[e.DistinctID] = true
		}
		return fmt.Sprintf("%s events total%s, from %s users, across %d event types.",
			commaInt(len(scoped)), winSuffix(win), commaInt(len(users)), len(volAll))
	}
	if ev := namedEvent(qe, volAll); ev != "" && (countish(q) || len(strings.Fields(q)) <= 3 || win.scoped()) &&
		intent != intentConvBy &&
		// retention/stickiness questions name an event ("retention for app_open", "app_open
		// stickiness") but must go to their OWN report — the count intercept used to hijack
		// them (with win.scoped()) and return an event VOLUME count stamped "retention report".
		intent != intentRetention && intent != intentStickiness && intent != intentLifecycle &&
		!hasAny(q, "by country", "by device", "by browser", "by os", "by source", "by referrer", "break down", "breakdown") &&
		!(intent == intentFunnel && (hasAny(q, "all the way", "made it", "complete", "end up", "go on to",
			"percent", "% of", "share of", "rate", "dropped between", "drop between", "funnel") ||
			// bare "convert"/"conversion" signals a funnel ONLY when it isn't the counted
			// event's OWN name — "how many convert events" is a count of the event "convert",
			// not a funnel request (explicit funnel words above still route to the funnel).
			(hasAny(q, "conversion", "convert") && !strings.Contains(strings.ToLower(ev), "conv")))) {
		// P2-5: if the event was resolved through a SYNONYM (the asked word isn't the
		// tracked name), disclose the substitution rather than silently answering it.
		if syn := synonymNote(q, ev); syn != "" {
			return syn + " " + answerEvent(scoped, ev, win, q)
		}
		return answerEvent(scoped, ev, win, q)
	}
	// If the user explicitly named an event ("the X event", "X events fire") that we
	// DON'T have, say so with the nearest real name — never silently fall through to a
	// default event and hand back an authoritative count for something they didn't ask
	// about. That substitution is the exact "trust your numbers" failure this product
	// sells against.
	if miss := unknownNamedEvent(q, volAll); miss != "" {
		return answerUnknownEvent(miss, volAll)
	}
	// P0-2: a COUNT question about a specific noun that is NOT a tracked event, a web
	// term, or a metric ("how many refunds", "how many burritos") must NOT fall through
	// to the signups/how-many catch-all and answer a different event's count under the
	// "cannot be fabricated" stamp. Only guard the intentSignups catch-all — every other
	// intent (active users, web, geo…) resolves its own noun correctly.
	if intent == intentSignups {
		if miss := unknownCountNoun(qe, volAll); miss != "" {
			return answerUnknownEvent(miss, volAll)
		}
	}

	return answerScopedIntent(intent, evs, scoped, volAll, win, now, q)
}

// answerScopedIntent dispatches the report-shaped intents; pulled out of answer so the
// segment layer can run the SAME reports over a filtered event set.
func answerScopedIntent(intent askIntent, evs []event.Event, scoped []event.Event, volAll []string, win askWindow, now time.Time, q string) string {
	switch intent {
	case intentRetention:
		// "how many people came back today" over a 1-2 day window is a returning-users
		// count over FULL history (first-seen needs it); a day-cohort rate over the
		// same window would have an empty denominator
		if win.scoped() && win.to.Sub(win.from) <= 48*time.Hour {
			return answerReturning(evs, q, win)
		}
		return answerRetention(scoped, volAll, win, now, q)
	case intentSources:
		for _, u := range []struct{ words, prop string }{
			{"utm medium", "utm_medium"}, {"utm source", "utm_source"}, {"utm campaign", "utm_campaign"},
		} {
			if strings.Contains(q, u.words) {
				return answerPropBreakdown(evs, u.prop, win)
			}
		}
		return answerSources(evs, win)
	case intentStickiness:
		return answerStickiness(evs, now)
	case intentPaths:
		return answerPaths(evs, q, volAll, win)
	case intentLifecycle:
		return answerLifecycle(evs, q, win, now)
	case intentHours:
		return answerHours(evs, win, now)
	case intentEntryPages:
		return answerEntryPages(evs, win)
	case intentPeakDay:
		return answerPeakDay(evs, resolveMetric(q, volAll), win, now)
	case intentSplit:
		return answerSplit(evs, q, win)
	case intentAI:
		return answerAIReferrers(evs, win)
	case intentConvBy:
		return answerConvByQ(evs, volAll, q, win)
	case intentChannels:
		return answerChannels(scoped, volAll, win)
	case intentTopPages:
		return answerTopPages(scoped, win)
	case intentGeo:
		if ev := namedEvent(normalizeEventWords(q), volAll); ev != "" {
			return answerPropBreakdownLabel(filterByName(scoped, ev), "country", ev+" users", win)
		}
		return answerGeo(scoped, evs, win)
	case intentWebDim:
		return answerWebDim(scoped, q, win)
	case intentEngagement:
		return answerEngagement(scoped, win)
	case intentLive:
		return answerLive(evs, now)
	case intentWeb:
		return answerWeb(scoped, win)
	case intentFunnel:
		return answerFunnel(scoped, volAll, win, q)
	case intentActive:
		if hasAny(q, "dau", "wau", "mau", "daily active", "weekly active", "monthly active") {
			return answerActiveUsers(evs, q, now)
		}
		return answerActive(scoped, win, now)
	case intentSignups:
		return answerSignups(scoped, volAll, win)
	default:
		// An unrecognized question must NAME the boundary before answering — refusing to
		// fabricate a metric we don't have is the single strongest trust move on the demo.
		// "what's my MRR?" silently returning a weekly digest reads exactly like a model
		// padding an answer, the very fear "plain-English analytics" triggers. So we say
		// what we don't invent, then offer the closest real report.
		return "I only answer from deterministic reports over the events you've sent, funnels, channels, " +
			"retention, signups, active users, top pages, pageviews. I don't invent metrics you haven't " +
			"tracked (revenue, MRR, churn) unless you send them as events. Here's the closest read I have:\n\n" +
			answerBrief(evs, 7, now) + "\n\nAsk about any of those, scoped to today, yesterday, this/last week, " +
			"this/last month, or last N days, or connect your own Claude/Cursor over MCP to go deeper."
	}
}

// normalizeEventWords maps the ways people write event names (plurals, spaced forms)
// onto the tracked names, so "signups this week vs last week" counts signup events
// instead of silently falling back to visitors.
var eventWordNorm = strings.NewReplacer(
	"sign-ups", "signup", "signups", "signup", "sign ups", "signup", "sign up", "signup", "signed up", "signup", "sign-up", "signup",
	"checkouts", "checkout", "checking out", "checkout", "checked out", "checkout", "check out", "checkout",
	"activations", "activate", "activation", "activate", "activated", "activate", "activating", "activate",
	"purchases", "purchase", "subscriptions", "subscribe", "subscribed", "subscribe",
	"opens", "open", "opened", "open",
)

func normalizeEventWords(q string) string { return eventWordNorm.Replace(q) }

// detectFunnelForConv picks the funnel steps for a "X vs Y conversion rate" question: the
// steps the user named ("signup to checkout conversion by plan") if present, else the
// auto-detected core funnel — so a rate comparison always has a real 2-step funnel to measure.
func detectFunnelForConv(evs []event.Event, vol []string, q string) []funnel.Step {
	if named := namedFunnelSteps(q, vol); len(named) >= 2 {
		return named
	}
	steps, _ := detectFunnel(evs, vol)
	return steps
}

// isTotalEventsAsk detects a question about TOTAL event volume across all events ("how many
// events did we receive", "total event volume") — as opposed to a count of one named event.
func isTotalEventsAsk(q string, vol []string) bool {
	if !hasAny(q, "event") {
		return false
	}
	if !hasAny(q, "how many event", "total event", "events all time", "events in total",
		"events altogether", "event volume", "events do we", "events did we", "events have we",
		"events received", "events receive", "count of events", "number of events") {
		return false
	}
	// if a specific tracked event name is present, the question is about THAT event, not the total.
	for _, n := range vol {
		if strings.Contains(q, strings.ToLower(n)) {
			return false
		}
	}
	return true
}

// commaInt formats an int with thousands separators (1200 -> "1,200").
func commaInt(n int) string {
	s := strconv.Itoa(n)
	neg := strings.HasPrefix(s, "-")
	if neg {
		s = s[1:]
	}
	var b strings.Builder
	for i, c := range s {
		if i > 0 && (len(s)-i)%3 == 0 {
			b.WriteByte(',')
		}
		b.WriteRune(c)
	}
	if neg {
		return "-" + b.String()
	}
	return b.String()
}

// isMeasureAsk spots a numeric-aggregation question (revenue, AOV, median, p90) vs a count.
// Kept to STRONG signals so "how much traffic" stays a web question, not a measure.
func isMeasureAsk(q string) bool {
	// engagement time is its own report — "avg session time" is not a numeric-property ask
	if hasAny(q, "session time", "time on site", "time on page", "session duration", "engaged", "engagement") {
		return false
	}
	if hasAny(q, "revenue", "order value", "aov", "arpu", "sum of", "median",
		"percentile", "p90", "p95", "p99", "average", "avg ", "mean ",
		"how much money", "how much did", "total spend", "total amount", "total revenue") {
		return true
	}
	// "total <event> amount", "sum of purchase amount", "average cart value" — a value-ish
	// property word paired with an aggregation word. Without this, "total checkout amount"
	// missed the measure route and was answered as a count / funnel (the wrong metric).
	if hasAny(q, "amount", "revenue", "spend", "cart value", "payment", "price paid") &&
		hasAny(q, "total ", "sum ", "how much", "average", "avg", "median", "add up") {
		return true
	}
	// superlatives count as a measure only when paired with a value-ish word, so "max amount"
	// / "highest revenue" route to a measure but "highest traffic" stays a web question.
	return hasAny(q, "highest", "lowest", "max ", "maximum", "minimum", "min ", "biggest", "largest", "smallest", "peak ") &&
		hasAny(q, "amount", "revenue", "value", "price", "cost", "spend", "order", "cart", "duration", "latency", "load time", "response time", "payment", "purchase")
}

// measureFromQuestion picks the aggregation from the phrasing; defaults to Sum (revenue).
func measureFromQuestion(q string) trends.Measure {
	switch {
	case hasAny(q, "average", "avg", "mean", "order value", "aov", "arpu"):
		return trends.Avg
	case hasAny(q, "median"):
		return trends.Median
	case hasAny(q, "p99"):
		return trends.P99
	case hasAny(q, "p95"):
		return trends.P95
	case hasAny(q, "p90", "percentile", "90th"):
		return trends.P90
	case hasAny(q, "highest", "max", "biggest", "largest", "peak"):
		return trends.Max
	case hasAny(q, "lowest", "min", "smallest"):
		return trends.Min
	default:
		return trends.Sum
	}
}

// resolveNumericProp maps the question to a numeric property that ACTUALLY EXISTS in the
// events, so we never invent a metric. Direct name match first, then aliases, then the usual
// money columns. Returns "" when nothing numeric fits — the honest-refusal path.
func resolveNumericProp(q string, evs []event.Event) string {
	props := trends.NumericProps(evs)
	if len(props) == 0 {
		return ""
	}
	has := func(name string) bool {
		for _, p := range props {
			if p == name {
				return true
			}
		}
		return false
	}
	for _, p := range props { // 1. a real numeric property named verbatim
		if strings.Contains(q, strings.ToLower(p)) {
			return p
		}
	}
	for _, a := range [][2]string{ // 2. aliases -> a candidate that exists
		{"revenue", "amount"}, {"order value", "amount"}, {"aov", "amount"}, {"sales", "amount"},
		{"spend", "amount"}, {"money", "amount"}, {"arpu", "amount"},
		{"latency", "duration_ms"}, {"load time", "duration_ms"}, {"duration", "duration_ms"},
		{"response time", "duration_ms"},
	} {
		if strings.Contains(q, a[0]) && has(a[1]) {
			return a[1]
		}
	}
	for _, c := range []string{"amount", "revenue", "value", "total", "price"} { // 3. usual columns
		if has(c) {
			return c
		}
	}
	return ""
}

// answerMeasure computes a numeric aggregate over a real property, or refuses honestly when
// no such property was sent — never fabricating a metric (the core trust promise).
func answerMeasure(evs []event.Event, q string, volAll []string, win askWindow) string {
	m := measureFromQuestion(q)
	prop := resolveNumericProp(q, evs)
	if prop == "" {
		if props := trends.NumericProps(evs); len(props) > 0 {
			return "I compute numbers only from values you've actually sent, so I won't invent one. The numeric properties on your events are: " +
				strings.Join(props, ", ") + ". Ask about one of those, or send a new one (e.g. track(\"checkout\", {amount: 29}))."
		}
		return "I compute numbers only from values you've actually sent, so I won't invent one. You haven't sent any numeric event properties yet — add one (e.g. track(\"checkout\", {amount: 29})) and I'll total or average it exactly."
	}
	ev := namedEvent(q, volAll) // "" = across every event carrying the property
	// honor any property qualifier ("average order value for pro users") — without filtering
	// by the named segment the measure was computed UNFILTERED, silently dropping the
	// qualifier and reporting a number for the wrong population as authoritative fact.
	pool := evs
	segLabel := ""
	for _, s := range extractSegments(q, evs) {
		if !s.found {
			return fmt.Sprintf("0 — no events with %s = %s have been sent, so there's no %s to compute for %s.", s.prop, s.label, prop, s.label)
		}
		if userAttr(s.prop) {
			pool = segFilterUsers(pool, s)
		} else {
			pool = segFilter(pool, s)
		}
		if segLabel == "" {
			segLabel = s.label
		} else {
			segLabel += " + " + s.label
		}
	}
	res := trends.ComputeMeasure(pool, ev, prop, m, win.from, win.to)
	// float64 overflow: never state "+Inf" as a fact with the CI-parity trailer — say what
	// happened, honestly, the same way /v1 and MCP now error on this input.
	if !res.Finite() {
		return fmt.Sprintf("The %s of %q overflows a float64 — the values are too large to aggregate exactly, so I won't report a made-up number. Check the property's unit (e.g. cents vs dollars, or a corrupted giant value in one event).", m, prop)
	}
	if res.N == 0 {
		seg := ""
		if segLabel != "" {
			seg = " for " + segLabel
		}
		return fmt.Sprintf("No numeric %q values%s in that window yet, so there's nothing to compute. Once your events carry it, I'll report it exactly.", prop, seg)
	}
	verb := map[trends.Measure]string{trends.Sum: "Total", trends.Avg: "Average", trends.Min: "Minimum", trends.Max: "Maximum", trends.Median: "Median", trends.P90: "p90", trends.P95: "p95", trends.P99: "p99"}[m]
	evPart := ""
	if ev != "" {
		evPart = " per " + ev
	}
	if segLabel != "" {
		evPart += " for " + segLabel
	}
	scopePart := ""
	if win.scoped() && win.label != "" {
		scopePart = ", " + strings.TrimSpace(win.label)
	}
	plural := "s"
	if res.N == 1 {
		plural = ""
	}
	return fmt.Sprintf("%s %s%s%s: %s, computed from %d event%s.", verb, prop, evPart, scopePart, fmtMeasureNum(res.Total), res.N, plural)
}

// fmtMeasureNum prints a whole number cleanly and anything else to 2 decimals.
func fmtMeasureNum(f float64) string {
	if f == math.Trunc(f) {
		return strconv.FormatFloat(f, 'f', 0, 64)
	}
	return strconv.FormatFloat(f, 'f', 2, 64)
}

// answerAction is honest guidance for change requests: the ask bar computes
// answers, it does not flip switches. Every branch names where the change
// actually lives, the Settings section and the MCP tool an agent can call.
func answerAction(q string) string {
	switch {
	case hasAny(q, "alert", "notify", "watch"):
		return "I can't create alerts from here, the ask bar only reads data. Set one up in Settings → Alerts " +
			"(wire a Slack/HTTPS destination under Settings → Webhooks first). In Cursor/Claude Code your " +
			"agent can do it directly: create_alert (\"tell me if signups drop below 10/day\")."
	case hasAny(q, "retention", "retain"):
		return "I can't change settings from here, data retention lives in Settings → Retention. " +
			"In Cursor/Claude Code your agent can: set_retention."
	case strings.Contains(q, "rename"):
		return "I can't rename events from here, event names come from your instrumentation. Rename it where " +
			"you call track(), then declare the new name in your tracking plan (set_tracking_plan in " +
			"Cursor/Claude Code) so drift gets flagged under Settings → Events tracked."
	default:
		return "The ask bar computes answers from your data, it can't change anything. Settings has the knobs " +
			"(retention, alerts, webhooks, API keys), and in Cursor/Claude Code your agent has the action " +
			"tools: create_alert, set_retention, create_goal, save_report."
	}
}

// briefDays maps the ask's phrasing to the brief's pulse width: "today" → 1,
// month phrasing → 30, else the weekly 7. brief.Build derives the
// current-vs-prior comparison windows from this.
func briefDays(q string) int {
	switch {
	case strings.Contains(q, "today"):
		return 1
	case strings.Contains(q, "month"):
		return 30
	default:
		return 7
	}
}

// answerBrief renders the SAME computation as `smolanalytics brief` (pulse +
// deltas + the verdict engine's findings) tight enough for the ask panel, one
// Brief struct feeds both, so the ask bar and the morning digest can never disagree.
func answerBrief(evs []event.Event, days int, now time.Time) string {
	b := brief.Build(evs, days, now)
	var s strings.Builder
	// b.Visitors counts distinct users of ANY event (active people), NOT web visitors
	// (pageviews) — label it as such so a 0-pageview site can't read "1 visitor this week"
	// and contradict the pageview-based web report.
	fmt.Fprintf(&s, "Last %d days: %d active people · %d events", b.Days, b.Visitors, b.Events)
	if b.PriorEvents == 0 {
		s.WriteString(" (no prior window to compare).")
	} else {
		people := "new"
		if b.PriorVisitors > 0 {
			people = fmt.Sprintf("%+d%%", pctChange(b.Visitors, b.PriorVisitors))
		}
		fmt.Fprintf(&s, " (vs prior %d days: active people %s, events %+d%%).", b.Days,
			people, pctChange(b.Events, b.PriorEvents))
	}
	if len(b.Findings) == 0 {
		s.WriteString(" Nothing notable, no big swings, funnel leaks, or retention flags.")
		return s.String()
	}
	s.WriteString("\nWhat to look at:")
	for _, f := range b.Findings {
		mark := "•"
		if f.Severity == "warn" {
			mark = "⚠"
		}
		fmt.Fprintf(&s, "\n%s %s, %s", mark, f.Title, f.Detail)
	}
	return s.String()
}

// pctChange mirrors brief's signed delta, direction must be unmissable.
func pctChange(cur, prior int) int {
	return int(math.Round(float64(cur-prior) / float64(prior) * 100))
}

// askWindow is an honest time scope parsed from the question. Zero from/to =
// all recorded history (the ask bar's long-standing default). The label is
// woven into every scoped answer so "this week" can never silently mean
// something else.
type askWindow struct {
	from, to time.Time
	label    string
}

func (w askWindow) scoped() bool { return !w.from.IsZero() || !w.to.IsZero() }

// windowClause weaves the computed window into a sentence: " this week (since
// Mon Jun 22, UTC)", or "" for all-time.
func windowClause(w askWindow) string {
	if !w.scoped() {
		return ""
	}
	return " " + w.label
}

var lastNDaysRe = regexp.MustCompile(`(?:last|past)\s+(\d+)\s+days?`)
var lastNHoursRe = regexp.MustCompile(`(?:last|past)\s+(\d+)\s+hours?`)
var lastNMinutesRe = regexp.MustCompile(`(?:last|past)\s+(\d+)\s+min(?:ute)?s?`)

// parseWindow maps time phrases to real windows (UTC, like every computation
// here). Recognized: today, yesterday, this/last week (calendar, Monday start),
// this/last month (calendar), and "last/past N days" (rolling, consistent with
// the engine). Anything else time-shaped (quarters, years, named months) comes
// back as unsupported so the caller can SAY so instead of silently answering
// over a different range.
func parseWindow(q string, now time.Time) (win askWindow, unsupported string) {
	const day = 24 * time.Hour
	today := now.Truncate(day)
	switch {
	case strings.Contains(q, "yesterday"):
		return askWindow{from: today.Add(-day), to: today, label: "yesterday (UTC)"}, ""
	case strings.Contains(q, "today"):
		return askWindow{from: today, to: now, label: "today (UTC)"}, ""
	case strings.Contains(q, "this week"):
		monday := today.AddDate(0, 0, -mondayOffset(today))
		return askWindow{from: monday, to: now,
			label: "this week (since Mon " + monday.Format("Jan 2") + ", UTC)"}, ""
	case strings.Contains(q, "last week"):
		monday := today.AddDate(0, 0, -mondayOffset(today))
		from := monday.AddDate(0, 0, -7)
		return askWindow{from: from, to: monday,
			label: "last week (Mon " + from.Format("Jan 2") + " – Sun " + monday.AddDate(0, 0, -1).Format("Jan 2") + ", UTC)"}, ""
	case strings.Contains(q, "past week"), strings.Contains(q, "previous week"):
		// calendar-day aligned (7 whole days ending today), identical to /v1/trends days=7
		// and the MCP tool, so every surface reports the same "last 7 days" number
		return askWindow{from: today.AddDate(0, 0, -6), to: now, label: "the last 7 days (UTC)"}, ""
	case strings.Contains(q, "past month"), strings.Contains(q, "previous month"):
		return askWindow{from: today.AddDate(0, 0, -29), to: now, label: "the last 30 days (UTC)"}, ""
	case strings.Contains(q, "this month"):
		first := time.Date(now.Year(), now.Month(), 1, 0, 0, 0, 0, time.UTC)
		return askWindow{from: first, to: now,
			label: "this month (since " + first.Format("Jan 2") + ", UTC)"}, ""
	case strings.Contains(q, "last month"):
		first := time.Date(now.Year(), now.Month(), 1, 0, 0, 0, 0, time.UTC)
		return askWindow{from: first.AddDate(0, -1, 0), to: first,
			label: "last month (" + first.AddDate(0, -1, 0).Format("January 2006") + ", UTC)"}, ""
	}
	if m := lastNMinutesRe.FindStringSubmatch(q); m != nil {
		// minute windows: "last 30 minutes" used to fall through to the empty (all-time)
		// window and answer the whole dataset under the "cannot be fabricated" stamp.
		if n, err := strconv.Atoi(m[1]); err == nil && n > 0 && n <= 60*24*366 {
			return askWindow{from: now.Add(-time.Duration(n) * time.Minute), to: now,
				label: fmt.Sprintf("the last %d minutes (UTC)", n)}, ""
		}
	}
	if m := lastNHoursRe.FindStringSubmatch(q); m != nil {
		if n, err := strconv.Atoi(m[1]); err == nil && n > 0 && n <= 24*366 {
			return askWindow{from: now.Add(-time.Duration(n) * time.Hour), to: now,
				label: fmt.Sprintf("the last %d hours (UTC)", n)}, ""
		}
	}
	if strings.Contains(q, "last hour") || strings.Contains(q, "past hour") {
		return askWindow{from: now.Add(-time.Hour), to: now, label: "the last hour (UTC)"}, ""
	}
	if m := lastNDaysRe.FindStringSubmatch(q); m != nil {
		if n, err := strconv.Atoi(m[1]); err == nil && n > 0 {
			// N whole calendar days ending today (from = midnight, n-1 days back), the
			// same window /v1/trends?days=N and the MCP trends tool use — so "last 7 days"
			// is one number across ask, API, MCP, and the dashboard tile.
			return askWindow{from: today.AddDate(0, 0, -(n - 1)), to: now,
				label: fmt.Sprintf("the last %d days (UTC)", n)}, ""
		}
	}
	if tok := unsupportedTimePhrase(q); tok != "" {
		return askWindow{}, tok
	}
	return askWindow{}, ""
}

// mondayOffset is days since the most recent Monday (0 on a Monday), Go's
// time.Weekday puts Sunday at 0, one off from a Monday-start week.
func mondayOffset(t time.Time) int { return (int(t.Weekday()) + 6) % 7 }

// unsupportedTimePhrase returns the first time-shaped token the parser does NOT
// support, so the answer can name it instead of quietly widening the window.
func unsupportedTimePhrase(q string) string {
	for _, tok := range []string{"quarter", "year", "month", "week", "hour", "minute",
		"q1", "q2", "q3", "q4", "january", "february", "march", "april", "june", "july",
		"august", "september", "october", "november", "december",
		"monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"} {
		if containsWord(q, tok) {
			return tok
		}
	}
	// "since <x>" and "best/worst day" are scope-shaped phrasings the parser doesn't
	// support — refuse them by name instead of silently answering the 30-day total.
	if strings.Contains(q, "since ") {
		return "since"
	}
	return ""
}

// containsWord reports whether tok appears as a whole word, "month" must not
// fire on "monthly", or every trend question would bounce as an unsupported window.
func containsWord(q, tok string) bool {
	isSep := func(r rune) bool { return !('a' <= r && r <= 'z' || '0' <= r && r <= '9') }
	for _, w := range strings.FieldsFunc(q, isSep) {
		if w == tok {
			return true
		}
	}
	return false
}

// scope keeps events inside [from, to), the end is exclusive so "yesterday"
// and "last week" never double-count the boundary instant.
func scope(evs []event.Event, w askWindow) []event.Event {
	if !w.scoped() {
		return evs
	}
	out := make([]event.Event, 0, len(evs))
	for _, e := range evs {
		if !w.from.IsZero() && e.Timestamp.Before(w.from) {
			continue
		}
		if !w.to.IsZero() && !e.Timestamp.Before(w.to) {
			continue
		}
		out = append(out, e)
	}
	return out
}

func answerFunnel(evs []event.Event, vol []string, win askWindow, q string) string {
	fsteps, ftitle := detectFunnel(evs, vol)
	// if the question explicitly NAMES the funnel steps ("what percent of landing users
	// convert"), honor exactly those in order — never the volume-detected funnel that
	// prepends the top event (pageview). Prepending a disjoint entry step (landing users who
	// never did pageview) zeroes the named step and falsely answers "No landing users".
	if named := namedFunnelSteps(q, vol); len(named) >= 2 {
		fsteps = named
		names := make([]string, len(named))
		for i, s := range named {
			names[i] = s.Event
		}
		ftitle = strings.Join(names, " → ")
	}
	fr := funnel.Compute(evs, fsteps, 7*24*time.Hour)
	if len(fr.Steps) == 0 || fr.Steps[0].Count == 0 {
		if win.scoped() {
			return "No events " + win.label + " to build a funnel from, widen the window, or drop the time phrase for all history."
		}
		return "No events yet to build a funnel from."
	}
	if len(fr.Steps) < 2 {
		// a single distinct event name means there's no funnel to measure yet, a bare
		// "signup → signup" would print an empty drop-off step with a -1 count. Answer
		// honestly and name the next action instead.
		return fmt.Sprintf("%d users did %q%s, that's the only event type tracked, so there's no funnel to measure yet. Add a later step (activate, checkout) to see where users drop off.",
			fr.Steps[0].Count, fr.Steps[0].Event, windowClause(win))
	}
	// step-pair sub-metrics: "signup to activation rate", "how many dropped between
	// activate and checkout" — answer the exact pair, not the whole-funnel headline
	if named := stepsInQuestion(q, fr); len(named) == 2 && named[0] < named[1] {
		a, b := fr.Steps[named[0]], fr.Steps[named[1]]
		if a.Count == 0 {
			return fmt.Sprintf("No %q users%s to compute a rate from.", a.Event, windowClause(win))
		}
		rate := int(float64(b.Count)/float64(a.Count)*100 + 0.5)
		if hasAny(q, "drop", "dropped", "fall off", "fell off", "lost", "lose") {
			return fmt.Sprintf("%d users dropped between %q and %q%s (%d → %d, %d%% continue).",
				a.Count-b.Count, a.Event, b.Event, windowClause(win), a.Count, b.Count, rate)
		}
		return fmt.Sprintf("%d%% of %q users go on to %q%s (%d of %d).",
			rate, a.Event, b.Event, windowClause(win), b.Count, a.Count)
	}
	// completers: "made it all the way through", "what percent of signups end up checking out"
	if hasAny(q, "all the way", "complete the funnel", "made it through", "finish the funnel",
		"end up", "full funnel", "whole funnel", "every step") {
		last := fr.Steps[len(fr.Steps)-1]
		return fmt.Sprintf("%d users completed the full funnel %s%s — %d%% of the %d who started.",
			last.Count, ftitle, windowClause(win), pct(fr.OverallConversion), fr.Steps[0].Count)
	}
	worst, worstDrop := "", -1
	for _, st := range fr.Steps[1:] {
		if st.DroppedFromPrev > worstDrop {
			worstDrop, worst = st.DroppedFromPrev, st.Event
		}
	}
	timing := ""
	if fr.Converted > 0 && fr.MedianConvSecs > 0 {
		timing = fmt.Sprintf(" Time to convert the full funnel: median %s, p90 %s (your slowest tenth take this long — a nudge/reminder targets them).",
			humanDuration(fr.MedianConvSecs), humanDuration(fr.P90ConvSecs))
	}
	return fmt.Sprintf("%d of %d users (%d%%) complete %s%s. The biggest drop-off is at \"%s\", %d users fall off there.%s",
		fr.Steps[len(fr.Steps)-1].Count, fr.Steps[0].Count, pct(fr.OverallConversion), ftitle, windowClause(win), worst, worstDrop, timing)
}

// humanDuration renders a time-to-convert like "45s", "12m", "3h 20m", or "2.5 days".
func humanDuration(secs float64) string {
	d := time.Duration(secs) * time.Second
	switch {
	case d < time.Minute:
		return fmt.Sprintf("%ds", int(d.Seconds()))
	case d < time.Hour:
		return fmt.Sprintf("%dm", int(d.Minutes()))
	case d < 24*time.Hour:
		h := int(d.Hours())
		if m := int(d.Minutes()) % 60; m != 0 {
			return fmt.Sprintf("%dh %dm", h, m)
		}
		return fmt.Sprintf("%dh", h)
	default:
		return fmt.Sprintf("%.1f days", d.Hours()/24)
	}
}

func answerRetention(evs []event.Event, vol []string, win askWindow, now time.Time, q string) string {

	// weekly/monthly/rolling asks take the bucketed path; the default daily path below is
	// kept byte-identical so nothing about the common case changes.
	if hasAny(q, "weekly", "week", "monthly", "month", "rolling", "unbounded") {
		return answerRetentionBucketed(evs, vol, win, now, q)
	}
	// anchor: ANY event ("" = general activity) by default — the same default /v1/retention
	// and the MCP tool use. But a question that NAMES an event ("retention for open") must
	// scope to it, matching GET/MCP retention?event=open — the named event used to be
	// silently ignored, answering a different question than the one asked.
	anchor := namedEvent(normalizeEventWords(q), vol)
	// "day 30 retention" widens the horizon to the asked day and answers honestly when
	// no cohort is old enough to observe it.
	askDay := retentionPeriodAsked(q)
	maxD := 7
	if askDay > maxD {
		maxD = askDay
	}
	rr := retention.Compute(evs, maxD, anchor)
	if askDay > 7 {
		dN, sizeN := retention.DayN(rr, askDay, now)
		if sizeN == 0 {
			return fmt.Sprintf("Not enough history to measure day-%d retention yet — no cohort is %d days old. The oldest data supports day-%d at most.", askDay, askDay, oldestObservableDay(rr, now))
		}
		return fmt.Sprintf("Day-%d retention is %d%% (of %d users old enough to measure, any activity counts as returning).",
			askDay, int(float64(dN)/float64(sizeN)*100+0.5), sizeN)
	}
	// honest denominators: only cohorts old enough to observe day N (retention.DayN)
	d1, size1 := retention.DayN(rr, 1, now)
	if size1 == 0 {
		if win.scoped() {
			return "Not enough history " + win.label + " to measure retention, day-1 retention needs users past " +
				"their first day. Widen the window, or drop the time phrase for all history."
		}
		return "Not enough history yet to measure retention, check back once users are past their first day."
	}
	out := fmt.Sprintf("Day-1 retention is %d%% (of %d users past day 1).",
		int(float64(d1)/float64(size1)*100+0.5), size1)
	if d7, size7 := retention.DayN(rr, 7, now); size7 > 0 {
		out = fmt.Sprintf("Day-1 retention is %d%% and day-7 is %d%% (of %d and %d users old enough to measure).",
			int(float64(d1)/float64(size1)*100+0.5), int(float64(d7)/float64(size7)*100+0.5), size1, size7)
	}
	if win.scoped() {
		out += " Cohorts scoped to first activity " + win.label + "."
	}
	return out
}

// answerRetentionBucketed handles weekly/monthly/rolling retention asks: same honest
// denominator (only cohorts old enough to observe period N), reported in the unit asked for.
func answerRetentionBucketed(evs []event.Event, vol []string, win askWindow, now time.Time, q string) string {
	bucket, unit, p1, p2, maxP := "day", "day", 1, 7, 7
	if hasAny(q, "weekly", "week") {
		bucket, unit, p1, p2, maxP = "week", "week", 1, 4, 4
	}
	if hasAny(q, "monthly", "month") {
		bucket, unit, p1, p2, maxP = "month", "month", 1, 3, 3
	}
	rolling := hasAny(q, "rolling", "unbounded")
	// same named-event scoping as the daily path: "weekly retention for open" anchors on
	// the open event, matching GET/MCP retention?event=open.
	anchor := namedEvent(normalizeEventWords(q), vol)
	rr := retention.ComputeBucketed(evs, maxP, anchor, bucket, rolling)

	r1, s1 := retention.PeriodN(rr, p1, now)
	kind := unit
	if rolling {
		kind = "rolling " + unit
	}
	if s1 == 0 {
		return fmt.Sprintf("Not enough history yet to measure %s-over-%s retention, cohorts need to be past their first %s. Check back later, or drop the bucket for daily retention.", kind, unit, unit)
	}
	pctOf := func(a, b int) int { return int(float64(a)/float64(b)*100 + 0.5) }
	out := fmt.Sprintf("%s-1 retention is %d%% (of %d users past %s 1).", title(unit), pctOf(r1, s1), s1, unit)
	if r2, s2 := retention.PeriodN(rr, p2, now); s2 > 0 {
		out = fmt.Sprintf("%s-1 retention is %d%% and %s-%d is %d%% (of %d and %d users old enough to measure).",
			title(unit), pctOf(r1, s1), unit, p2, pctOf(r2, s2), s1, s2)
	}
	if rolling {
		out += " (Rolling: counts users active on that period or any later one.)"
	}
	if win.scoped() {
		out += " Cohorts scoped to first activity " + win.label + "."
	}
	return out
}

// title upper-cases the first letter (day -> Day) for the sentence-start unit label.
func title(s string) string {
	if s == "" {
		return s
	}
	return strings.ToUpper(s[:1]) + s[1:]
}

// answerChannels answers "which channel converts best" the way goal_report does:
// first-touch attribution per user, then per-source conversion to the site's
// conversion event, NOT the funnel, which ignores sources entirely.
func answerChannels(evs []event.Event, vol []string, win askWindow) string {
	if len(evs) == 0 {
		if win.scoped() {
			return "No events " + win.label + " to attribute, widen the window, or drop the time phrase for all history."
		}
		return "No events recorded yet."
	}
	conv := pickConversion(evs, vol)

	// first-touch: a user's channel comes from their FIRST event, read from the best
	// available signal — source, else the referrer host, else utm_source, else direct.
	// Keying off a single "source" property collapsed everyone to "direct" on real
	// autocapture data (where the landing $pageview carries `referrer`, not `source`),
	// which is exactly the misleading "direct 220 users" answer this fixes.
	firstTS := map[string]time.Time{}
	firstSrc := map[string]string{}
	converted := map[string]bool{}
	anySignal := false
	for _, e := range evs {
		if t, ok := firstTS[e.DistinctID]; !ok || e.Timestamp.Before(t) {
			firstTS[e.DistinctID] = e.Timestamp
			ch := channelOf(e)
			if ch != "direct" {
				anySignal = true
			}
			firstSrc[e.DistinctID] = ch
		}
		if e.Name == conv {
			converted[e.DistinctID] = true
		}
	}
	if !anySignal {
		return "Every visitor here is untagged (no referrer, source, or utm on their first event), so there's " +
			"nothing to attribute a channel from — they'd all read as \"direct\". Tag inbound links with utm_source, " +
			"or make sure the SDK captures the referrer, and ask again."
	}
	type row struct {
		src              string
		users, converted int
	}
	bySrc := map[string]*row{}
	for id, src := range firstSrc {
		r := bySrc[src]
		if r == nil {
			r = &row{src: src}
			bySrc[src] = r
		}
		r.users++
		if converted[id] {
			r.converted++
		}
	}
	rows := make([]*row, 0, len(bySrc))
	for _, r := range bySrc {
		rows = append(rows, r)
	}
	// listing is volume-ordered (name breaks ties → deterministic run to run)
	sort.Slice(rows, func(i, j int) bool {
		if rows[i].users != rows[j].users {
			return rows[i].users > rows[j].users
		}
		return rows[i].src < rows[j].src
	})
	if len(converted) == 0 {
		// no conversions yet — just rank the channels by volume, no "best" to name
		parts := []string{}
		for i, r := range rows {
			if i >= 3 {
				break
			}
			parts = append(parts, fmt.Sprintf("%s %d users", r.src, r.users))
		}
		return fmt.Sprintf("By channel, first-touch%s: %s. No %q conversions in this data yet, so there is no honest \"best\" to rank.",
			windowClause(win), strings.Join(parts, ", "), conv)
	}
	// "best" = highest conversion rate; users break ties so a bigger sample wins
	rateOf := func(r *row) float64 { return float64(r.converted) / float64(r.users) }
	best := rows[0]
	for _, r := range rows[1:] {
		if rateOf(r) > rateOf(best) || (rateOf(r) == rateOf(best) && r.users > best.users) {
			best = r
		}
	}
	// the listing shows the top channels AND always includes the named winner, so the
	// channel we call "best" never goes missing from the evidence list beneath it.
	parts := []string{}
	shown := map[string]bool{}
	for i, r := range rows {
		if i >= 3 {
			break
		}
		parts = append(parts, fmt.Sprintf("%s %d users → %d %s (%d%%)",
			r.src, r.users, r.converted, conv, int(rateOf(r)*100+0.5)))
		shown[r.src] = true
	}
	if !shown[best.src] {
		parts = append(parts, fmt.Sprintf("%s %d users → %d %s (%d%%)",
			best.src, best.users, best.converted, conv, int(rateOf(best)*100+0.5)))
	}
	listing := fmt.Sprintf("By channel, first-touch%s: %s.", windowClause(win), strings.Join(parts, ", "))
	return fmt.Sprintf("%s converts best to \"%s\": %d of %d first-touch users (%d%%). %s",
		best.src, conv, best.converted, best.users, int(rateOf(best)*100+0.5), listing)
}

// genericSource is true for source values that carry NO acquisition signal — a platform
// tag ("web"/"app"/"mobile") or a placeholder — so they must not win over the referrer
// host. Without this, a uniform source:"web" on the first event re-collapses every
// channel into "web" and undoes first-touch attribution entirely.
func genericSource(s string) bool {
	switch strings.ToLower(strings.TrimSpace(s)) {
	case "", "web", "app", "mobile", "desktop", "direct", "unknown", "none", "server":
		return true
	}
	return false
}

// channelOf reads a visitor's acquisition channel from an event, best signal first: an
// explicit ACQUISITION source, else the referrer host, else utm_source, else direct.
// A generic platform source ("web"/"app") is skipped so it can't mask the real referrer.
func channelOf(e event.Event) string {
	if s, _ := e.Properties["source"].(string); s != "" && !genericSource(s) {
		return s
	}
	if r, _ := e.Properties["referrer"].(string); r != "" {
		if h := hostOf(r); h != "" {
			return h
		}
	}
	if u, _ := e.Properties["utm_source"].(string); u != "" {
		return u
	}
	return "direct"
}

// pickConversion picks the event "converts" means for this dataset: the
// conventional conversion names when present, else the deepest step of the
// auto-detected journey funnel. The answer always names it, so the user sees
// exactly what was computed.
func pickConversion(evs []event.Event, vol []string) string {
	for _, want := range []string{"signup", "purchase", "checkout", "subscribe", "convert", "activate"} {
		if hasName(vol, want) {
			return want
		}
	}
	if steps, _ := detectFunnel(evs, vol); len(steps) > 0 {
		return steps[len(steps)-1].Event
	}
	return ""
}

// windowDays is the honest denominator for a per-day rate. len(trend.Points)
// includes the exclusive end-boundary's bucket, so it overstates the divisor by
// one and understates the rate (291 over a 7-day week read as 36/day, not 42).
// For a scoped window, count the whole days it actually spans; otherwise the
// point count is the day count.
// rateSuffix renders ", about N/day" only when the window is long enough for a
// daily rate to mean anything — "49 events yesterday, about 49/day" was noise,
// and a 6-hour window divided into days is nonsense.
func rateSuffix(total int, win askWindow, points int) string {
	d := windowDays(win, points)
	if d < 2 {
		return ""
	}
	// float rate, not truncating integer division: 4 events over 7 days is 0.57/day, which
	// floored to "about 0/day" reads as "nothing happened" for a non-zero count. Describe a
	// real-but-sub-1 rate honestly instead of flooring it to a misleading zero.
	rate := float64(total) / float64(d)
	if total > 0 && rate < 1 {
		return ", less than 1/day"
	}
	return fmt.Sprintf(", about %d/day", int(rate+0.5))
}

func windowDays(win askWindow, points int) int {
	if win.scoped() {
		d := int(win.to.Sub(win.from).Hours()/24 + 0.5)
		if d < 1 {
			d = 1
		}
		return d
	}
	if points < 1 {
		return 1
	}
	return points
}

// lastNDays renders "the last N days" with correct grammar (1 → "day") and a clean
// "today so far" for the degenerate 1-bucket case, so a day-old account never reads
// "over the last 1 days" or "over 0 days".
// allTimeSpan labels an UNSCOPED (all-history) total honestly. It must NOT borrow the
// "last N days" phrasing — that reads as a bounded window and made the same total render
// as "104 over the last 7 days" (all-time) vs "101 in the last 7 days" (actually bounded),
// two different numbers under one label. This says plainly it's the whole history.
func allTimeSpan(n int) string {
	if n <= 1 {
		return "all time"
	}
	return fmt.Sprintf("all time (%d days of history)", n)
}

func answerSignups(evs []event.Event, vol []string, win askWindow) string {
	ev := pickEvent(vol, "signup")
	if ev == "" {
		return "No events recorded yet."
	}
	tr := trends.Compute(evs, ev, win.from, win.to, false)
	days := len(tr.Points)
	if days == 0 {
		return "No events recorded yet."
	}
	if tr.Total == 0 && win.scoped() {
		return fmt.Sprintf("No \"%s\" events %s, widen the window, or drop the time phrase for all history.", ev, win.label)
	}
	if win.scoped() {
		return fmt.Sprintf("%d \"%s\" events %s%s.", tr.Total, ev, win.label, rateSuffix(tr.Total, win, days))
	}
	return fmt.Sprintf("%d \"%s\" events %s%s.", tr.Total, ev, allTimeSpan(days), rateSuffix(tr.Total, win, days))
}

func answerActive(evs []event.Event, win askWindow, now time.Time) string {
	if win.scoped() {
		users := distinctUsers(evs)
		if users == 0 {
			return "No active users " + win.label + ", widen the window, or drop the time phrase for all history."
		}
		return fmt.Sprintf("%d active users %s, across %d events.", users, win.label, len(evs))
	}
	total := distinctUsers(evs)
	cutoff := now.AddDate(0, 0, -7)
	recent := map[string]bool{}
	for _, e := range evs {
		if !e.Timestamp.Before(cutoff) { // inclusive "last 7 days", consistent with the engine
			recent[e.DistinctID] = true
		}
	}
	return fmt.Sprintf("%d total users, %d active in the last 7 days.", total, len(recent))
}

// answerEvent counts one named event over the window, the resolver for "how many
// checkout this week?" and the "your events" discovery chips. Mirrors answerSignups
// but for the exact event the user named rather than the picked default.
func answerEvent(evs []event.Event, ev string, win askWindow, q string) string {
	// "how many UNIQUE/DISTINCT users did X" wants deduped users, not the raw event count —
	// the engine computes both; answering the count for a users-phrased question overstates it.
	unique := hasAny(q, "unique user", "distinct user", "unique people", "distinct people",
		"how many users", "how many people", "users did", "people did", "users who", "people who")
	tr := trends.Compute(evs, ev, win.from, win.to, unique)
	days := len(tr.Points)
	unit := "events"
	if unique {
		unit = "distinct users"
	}
	if tr.Total == 0 {
		if win.scoped() {
			return fmt.Sprintf("No %q %s %s. Widen the window, or drop the time phrase for all history.", ev, unit, win.label)
		}
		return fmt.Sprintf("No %q %s recorded yet.", ev, unit)
	}
	if win.scoped() {
		return fmt.Sprintf("%d %q %s %s%s.", tr.Total, ev, unit, win.label, rateSuffix(tr.Total, win, days))
	}
	return fmt.Sprintf("%d %q %s %s%s.", tr.Total, ev, unit, allTimeSpan(days), rateSuffix(tr.Total, win, days))
}

// answerPage answers "visitors to /pricing" / "how many pageviews for /pqr" from
// autocaptured $pageview events. Path match is case- and trailing-slash-insensitive
// so the user never has to remember the exact casing.
func answerPage(evs []event.Event, path string, win askWindow) string {
	target := normPath(path)
	visitors := map[string]bool{}
	views := 0
	for _, e := range evs {
		if e.Name != "$pageview" {
			continue
		}
		p, _ := e.Properties["path"].(string)
		if normPath(p) != target {
			continue
		}
		views++
		if e.DistinctID != "" {
			visitors[e.DistinctID] = true
		}
	}
	if views == 0 {
		return fmt.Sprintf("No pageviews for %s%s. Double-check the path, or ask \"top pages\" to see what's tracked.", path, winSuffix(win))
	}
	return fmt.Sprintf("%s%s: %d visitors, %d pageviews.", path, winSuffix(win), len(visitors), views)
}

// answerWeb answers "how many pageviews / visitors / traffic" from autocaptured
// $pageview events — the fix for the router answering a signup count when the user
// asked about pageviews. Counts views and the distinct visitors behind them.

// answerWebDim answers device/browser/os/bounce questions from the same web report
// the dashboard renders — the ask bar must never deny a dimension the dashboard shows.

// answerEngagement reports engaged visitors + average engaged time over the window,
// from the SDK's $engagement events (visible AND focused time — background tabs
// don't count). The metric evaluators actually ask for by name.
func answerEngagement(evs []event.Event, win askWindow) string {
	perUser := map[string]float64{}
	for _, e := range evs {
		if e.Name != "$engagement" {
			continue
		}
		if ms, ok := e.Properties["engaged_ms"].(float64); ok && ms > 0 {
			perUser[e.DistinctID] += ms
		}
	}
	if len(perUser) == 0 {
		if win.scoped() {
			return "No engagement measured " + win.label + ". Engagement comes from the SDK's $engagement events (visible + focused time) — widen the window, or drop the time phrase for all history."
		}
		return "No engagement data yet. The browser SDK measures it automatically once installed (visible + focused time per visitor)."
	}
	var total float64
	for _, ms := range perUser {
		total += ms
	}
	avgSecs := int(total / float64(len(perUser)) / 1000)
	human := fmt.Sprintf("%ds", avgSecs)
	if avgSecs >= 60 {
		human = fmt.Sprintf("%dm %ds", avgSecs/60, avgSecs%60)
	}
	scope := "across all recorded history"
	if win.scoped() {
		scope = win.label
	}
	return fmt.Sprintf("%d engaged visitors %s, averaging %s of active time each (visible and focused — background tabs don't count).", len(perUser), scope, human)
}

func answerWebDim(evs []event.Event, q string, win askWindow) string {
	pick := func(prop string) []struct {
		v string
		n int
	} {
		// count VISITORS first-touch (each visitor's earliest pageview, once), IDENTICAL
		// to web.Compute — counting raw pageviews made the ask split (6/3) disagree with
		// the dashboard/GET/MCP visitor split (5/2) for the same question.
		firstPV := map[string]event.Event{}
		for _, e := range evs {
			if e.Name != "$pageview" {
				continue
			}
			if f, ok := firstPV[e.DistinctID]; !ok || e.Timestamp.Before(f.Timestamp) {
				firstPV[e.DistinctID] = e
			}
		}
		counts := map[string]int{}
		for _, e := range firstPV {
			if val, _ := e.Properties[prop].(string); val != "" {
				counts[val]++
			}
		}
		type kv struct {
			v string
			n int
		}
		rows := make([]kv, 0, len(counts))
		for v, n := range counts {
			rows = append(rows, kv{v, n})
		}
		sort.Slice(rows, func(i, j int) bool { return rows[i].n > rows[j].n })
		out := make([]struct {
			v string
			n int
		}, 0, len(rows))
		for i, r := range rows {
			if i == 5 {
				break
			}
			out = append(out, struct {
				v string
				n int
			}{r.v, r.n})
		}
		return out
	}
	label, prop := "devices", "device"
	switch {
	case strings.Contains(q, "browser"):
		label, prop = "browsers", "browser"
	case strings.Contains(q, "os"), strings.Contains(q, "operating system"):
		label, prop = "operating systems", "os"
	case strings.Contains(q, "bounce"):
		// bounce rate: one-pageview visitors who engaged under 10s (the web report's rule)
		pv := map[string]int{}
		eng := map[string]float64{}
		for _, e := range evs {
			if e.Name == "$pageview" {
				pv[e.DistinctID]++
			} else if e.Name == "$engagement" {
				if ms, _ := e.Properties["engaged_ms"].(float64); ms > 0 {
					eng[e.DistinctID] += ms
				}
			}
		}
		if len(pv) == 0 {
			return "No pageviews" + winSuffix(win) + " to measure bounce rate."
		}
		bounced := 0
		for u, n := range pv {
			if n == 1 && eng[u] < 10000 {
				bounced++
			}
		}
		return fmt.Sprintf("Bounce rate is %d%% (%d of %d visitors left after one page in under 10s)%s.", int(float64(bounced)/float64(len(pv))*100+0.5), bounced, len(pv), winSuffix(win))
	}
	rows := pick(prop)
	if len(rows) == 0 {
		return "No " + label + " recorded" + winSuffix(win) + " yet — these are parsed from the user agent at ingest, so they appear as visitors arrive."
	}
	parts := make([]string, len(rows))
	for i, r := range rows {
		parts[i] = fmt.Sprintf("%s (%d)", r.v, r.n)
	}
	// "by visitors": the numbers are first-touch visitor counts (the dashboard's unit),
	// not pageviews — say so, so the unit can't be misread.
	return "Top " + label + " by visitors" + winSuffix(win) + ": " + strings.Join(parts, ", ") + "."
}

// answerLive answers "who's on the site right now" from the last-5-minute window,
// the same live count the dashboard header shows.
func answerLive(evs []event.Event, now time.Time) string {
	cutoff := now.Add(-5 * time.Minute)
	live := map[string]bool{}
	for _, e := range evs {
		if e.Name == "$pageview" && !e.Timestamp.Before(cutoff) {
			live[e.DistinctID] = true
		}
	}
	if len(live) == 0 {
		return "Nobody on the site in the last 5 minutes."
	}
	if len(live) == 1 {
		return "1 visitor on the site right now (active in the last 5 minutes)."
	}
	return fmt.Sprintf("%d visitors on the site right now (active in the last 5 minutes).", len(live))
}

func answerWeb(evs []event.Event, win askWindow) string {
	visitors := map[string]bool{}
	views := 0
	for _, e := range evs {
		if e.Name != "$pageview" {
			continue
		}
		views++
		if e.DistinctID != "" {
			visitors[e.DistinctID] = true
		}
	}
	if views == 0 {
		// autocapture uses "$pageview", but some products track a CUSTOM event literally
		// named "pageview"/"page_view". Count that rather than falsely reporting "No
		// pageviews" while 20 such events sit in the log.
		for _, name := range []string{"pageview", "page_view"} {
			cv, cu := 0, map[string]bool{}
			for _, e := range evs {
				if e.Name == name {
					cv++
					cu[e.DistinctID] = true
				}
			}
			if cv > 0 {
				return fmt.Sprintf("%d %q events from %d users%s. (These are a custom %q event, not autocaptured $pageview.)", cv, name, len(cu), winSuffix(win), name)
			}
		}
		if win.scoped() {
			return "No pageviews " + win.label + ". The browser snippet autocaptures $pageview events — widen the window, or drop the time phrase for all history."
		}
		return "No pageviews recorded yet. The browser snippet autocaptures $pageview events — check it's installed on your site."
	}
	return fmt.Sprintf("%d pageviews from %d visitors%s.", views, len(visitors), winSuffix(win))
}

// answerTopPages ranks the most-viewed paths from $pageview events — the answer for
// "top pages" / "most visited", which used to deflect to the capabilities menu.
func answerTopPages(evs []event.Event, win askWindow) string {
	views := map[string]int{}
	for _, e := range evs {
		if e.Name != "$pageview" {
			continue
		}
		p, _ := e.Properties["path"].(string)
		if p == "" {
			p = "(no path)"
		}
		views[normPath(p)]++
	}
	if len(views) == 0 {
		if win.scoped() {
			return "No pageviews " + win.label + " to rank. Widen the window, or drop the time phrase for all history."
		}
		return "No pageviews recorded yet to rank. The browser snippet autocaptures $pageview events."
	}
	type pageRow struct {
		path string
		n    int
	}
	rows := make([]pageRow, 0, len(views))
	for p, n := range views {
		rows = append(rows, pageRow{p, n})
	}
	sort.Slice(rows, func(i, j int) bool {
		if rows[i].n != rows[j].n {
			return rows[i].n > rows[j].n
		}
		return rows[i].path < rows[j].path
	})
	parts := []string{}
	for i, r := range rows {
		if i >= 5 {
			break
		}
		parts = append(parts, fmt.Sprintf("%s (%d)", r.path, r.n))
	}
	return fmt.Sprintf("Top pages by pageviews%s: %s.", winSuffix(win), strings.Join(parts, ", "))
}

// extractPath pulls a URL path token ("/pricing") out of a question, so "visitors to
// /pricing?" resolves to /pricing. Returns "" when no path is mentioned.
func extractPath(q string) string {
	for _, w := range strings.Fields(q) {
		if strings.HasPrefix(w, "/") && len(w) > 1 {
			return strings.TrimRight(w, "?.,!\"')")
		}
	}
	return ""
}

// normPath lower-cases and strips a trailing slash so "/Pricing" and "/pricing/"
// both match the stored "/pricing".
func normPath(p string) string {
	p = strings.ToLower(strings.TrimSpace(p))
	if len(p) > 1 {
		p = strings.TrimRight(p, "/")
	}
	return p
}

// namedEvent returns the first (highest-volume) real event name the question mentions
// as a whole token. Skips $-prefixed internal events (those are pages, handled by path).
func namedEvent(q string, vol []string) string {
	toks := map[string]bool{}
	for _, w := range strings.Fields(q) {
		toks[strings.Trim(w, "?.,!\"'()")] = true
	}
	for _, ev := range vol {
		if strings.HasPrefix(ev, "$") {
			continue
		}
		if toks[strings.ToLower(ev)] {
			return ev
		}
	}
	// autocapture synonyms: "clicks" means $click (nobody types the dollar sign)
	if hasAny(q, "clicks", "click count", "how many click") {
		for _, ev := range vol {
			if ev == "$click" {
				return ev
			}
		}
	}
	// purchase synonyms map to a real purchase-shaped event so "how many purchases"
	// answers about checkout/order/payment instead of silently falling to signups
	if hasAny(q, "purchase", "bought", "buy", "order", "sale", "revenue event", "payment") {
		for _, want := range []string{"checkout", "purchase", "order", "payment", "buy", "sale"} {
			for _, ev := range vol {
				if strings.ToLower(ev) == want {
					return ev
				}
			}
		}
	}
	return ""
}

// unknownNamedEvent returns an event-shaped token the user explicitly asked about
// ("the flibbergibbet event", "how many zorptastic events fired") that is NOT in the
// dataset — so the caller can answer honestly instead of substituting a default event.
// It only fires on the explicit "<token> event(s)" pattern to avoid bouncing generic
// asks ("how many signups"): the word "event"/"events" must sit next to the token, and
// the token must not itself be a known event (that case is answerEvent's) or a generic
// metric/filler word.
func unknownNamedEvent(q string, vol []string) string {
	known := map[string]bool{}
	for _, ev := range vol {
		known[strings.ToLower(ev)] = true
	}
	words := strings.Fields(q)
	for i, w := range words {
		bare := strings.ToLower(strings.Trim(w, "?.,!\"'()"))
		if bare != "event" && bare != "events" {
			continue
		}
		// the candidate is the neighbouring noun: "the X event" (before) or
		// "X events fire" (also before). Fall back to the word after when the word
		// before is filler ("the", "an").
		var cand string
		if i > 0 {
			cand = strings.ToLower(strings.Trim(words[i-1], "?.,!\"'()"))
		}
		if (cand == "" || isFillerWord(cand)) && i+1 < len(words) {
			cand = strings.ToLower(strings.Trim(words[i+1], "?.,!\"'()"))
		}
		if cand == "" || isFillerWord(cand) || known[cand] || cand == "event" || cand == "events" {
			continue
		}
		return cand
	}
	return ""
}

// synonymNote returns a one-line disclosure when the event was resolved through a
// synonym (the tracked name does NOT appear literally in the question), so a
// substituted answer is never presented as if the user's exact word was the event.
// Empty when the user typed the real event name (or its plural) — no note needed.
func synonymNote(q, ev string) string {
	low := strings.ToLower(ev)
	if strings.Contains(q, low) || strings.Contains(q, low+"s") {
		return ""
	}
	return fmt.Sprintf("You don't track that exact event, so here's the closest one you do — %q:", ev)
}

// countNounRe pulls the noun out of the common count phrasings so an unknown one can
// be caught: "how many <noun>", "number of <noun>", "<noun> count".
var countHowManyRe = regexp.MustCompile(`how many ([a-z][a-z-]{2,})`)
var countNumberOfRe = regexp.MustCompile(`number of ([a-z][a-z-]{2,})`)

// webCountNouns are the count-nouns that belong to OTHER intents (web/active/etc), so
// the unknown-event miss must not fire on them.
var webCountNouns = map[string]bool{
	"visitor": true, "visitors": true, "visit": true, "visits": true, "view": true,
	"views": true, "pageview": true, "pageviews": true, "people": true, "person": true,
	"folks": true, "user": true, "users": true, "session": true, "sessions": true,
	"click": true, "clicks": true, "hit": true, "hits": true, "event": true, "events": true,
	"country": true, "countries": true, "day": true, "days": true, "hour": true, "hours": true,
	"time": true, "times": true, "page": true, "pages": true, "referrer": true, "referrers": true,
	"source": true, "sources": true, "signup": true, "signups": true,
}

// unknownCountNoun returns a count-noun the user asked to COUNT that is not a tracked
// event, not a web/metric term, and not filler — so the caller can miss honestly
// instead of substituting the signups/how-many catch-all. Empty when the noun is
// known or the question isn't a bare count of one noun.
func unknownCountNoun(qe string, vol []string) string {
	known := map[string]bool{}
	for _, ev := range vol {
		known[strings.ToLower(ev)] = true
	}
	var cand string
	if m := countHowManyRe.FindStringSubmatch(qe); m != nil {
		cand = m[1]
	} else if m := countNumberOfRe.FindStringSubmatch(qe); m != nil {
		cand = m[1]
	}
	if cand == "" {
		return ""
	}
	sing := strings.TrimSuffix(cand, "s")
	if isFillerWord(cand) || webCountNouns[cand] || webCountNouns[sing] ||
		known[cand] || known[sing] || namedEvent(cand, vol) != "" {
		return ""
	}
	return cand
}

// isFillerWord skips articles/generic nouns so "the ... event" resolves to the real
// name token, not to "the" or "many".
func isFillerWord(w string) bool {
	switch w {
	case "the", "a", "an", "any", "each", "this", "that", "my", "your", "which",
		"what", "how", "many", "much", "number", "count", "total", "of", "did",
		"does", "do", "fire", "fired", "fires", "named", "called", "custom":
		return true
	}
	return false
}

// answerUnknownEvent tells the user the named event doesn't exist and points at the
// nearest real name (and the discovery chips) rather than answering a substitute.
func answerUnknownEvent(name string, vol []string) string {
	real := make([]string, 0, len(vol))
	for _, ev := range vol {
		if !strings.HasPrefix(ev, "$") {
			real = append(real, ev)
		}
	}
	if len(real) == 0 {
		return fmt.Sprintf("No event named %q — in fact no product events are recorded yet. Send some with track(), then ask again.", name)
	}
	if near := nearestEvent(name, real); near != "" {
		return fmt.Sprintf("No event named %q. Did you mean %q? Your tracked events: %s.", name, near, strings.Join(cap8(real), ", "))
	}
	return fmt.Sprintf("No event named %q. Your tracked events: %s. Ask about one of those.", name, strings.Join(cap8(real), ", "))
}

// cap8 trims a listing to eight names so the answer stays one line.
func cap8(names []string) []string {
	if len(names) > 8 {
		return names[:8]
	}
	return names
}

// nearestEvent returns the closest real event name to the mistyped one by edit
// distance, but only when it's a plausible typo (distance ≤ 40% of the name) — a
// wild miss ("flibbergibbet") gets no misleading suggestion.
func nearestEvent(name string, real []string) string {
	best, bestD := "", 1<<30
	for _, ev := range real {
		d := levenshtein(name, strings.ToLower(ev))
		if d < bestD {
			best, bestD = ev, d
		}
	}
	if best == "" {
		return ""
	}
	limit := len(name) * 2 / 5
	if limit < 1 {
		limit = 1
	}
	if bestD <= limit {
		return best
	}
	return ""
}

// levenshtein is the standard edit distance, small strings only (event names), so a
// simple two-row DP is plenty.
func levenshtein(a, b string) int {
	ra, rb := []rune(a), []rune(b)
	prev := make([]int, len(rb)+1)
	cur := make([]int, len(rb)+1)
	for j := range prev {
		prev[j] = j
	}
	for i := 1; i <= len(ra); i++ {
		cur[0] = i
		for j := 1; j <= len(rb); j++ {
			cost := 1
			if ra[i-1] == rb[j-1] {
				cost = 0
			}
			cur[j] = min3(cur[j-1]+1, prev[j]+1, prev[j-1]+cost)
		}
		prev, cur = cur, prev
	}
	return prev[len(rb)]
}

func min3(a, b, c int) int {
	if b < a {
		a = b
	}
	if c < a {
		a = c
	}
	return a
}

// countish reports whether the question is asking for a count/volume, so a bare
// event mention ("how is checkout doing") still falls through to the funnel intent.
func countish(q string) bool {
	return hasAny(q, "how many", "how much", "count", "number of", "total", "mau", "dau", "wau",
		"monthly active", "daily active", "weekly active")
}

// winSuffix renders " <label>" for a scoped window, "" otherwise.
func winSuffix(w askWindow) string {
	if w.scoped() && w.label != "" {
		return " " + w.label
	}
	return ""
}

func hasAny(s string, subs ...string) bool {
	for _, sub := range subs {
		if strings.Contains(s, sub) {
			return true
		}
	}
	return false
}

// answerGeo counts distinct visitor countries (ingest-time geo). Geo stamping
// began when the operator's instance first ran a geo-enabled build and IPs are
// never stored, so history before that carries no country — the answer SAYS so
// whenever the asked window predates the first stamped event, instead of letting
// an honest small number read as a broken one.
func answerGeo(scoped, all []event.Event, win askWindow) string {
	type cAgg struct {
		visitors map[string]bool
		views    int
	}
	byCC := map[string]*cAgg{}
	unknownV := map[string]bool{} // geo ran but the IP resolved to ZZ/XX (proxy/anon) — never a real country
	for _, e := range scoped {
		if e.Name != "$pageview" {
			continue
		}
		cc, _ := e.Properties["country"].(string)
		if cc == "" {
			continue
		}
		if cc == "ZZ" || cc == "XX" {
			unknownV[e.DistinctID] = true // count as unresolved, never render "ZZ" as a country (the dashboard hides it as Unknown — the ask bar must agree)
			continue
		}
		a := byCC[cc]
		if a == nil {
			a = &cAgg{visitors: map[string]bool{}}
			byCC[cc] = a
		}
		a.views++
		a.visitors[e.DistinctID] = true
	}
	// the honesty clause: when did geo stamping actually begin on this instance?
	var firstGeo time.Time
	for _, e := range all {
		if _, ok := e.Properties["country"].(string); ok {
			if firstGeo.IsZero() || e.Timestamp.Before(firstGeo) {
				firstGeo = e.Timestamp
			}
		}
	}
	note := ""
	if !firstGeo.IsZero() && (!win.scoped() || win.from.Before(firstGeo)) {
		note = " Geo stamping began " + firstGeo.Format("Jan 2") + " on this instance (the IP is used for one lookup at ingest and never stored), so earlier events carry no country."
	}
	if len(byCC) == 0 {
		if firstGeo.IsZero() {
			return "No country data yet. Geo stamps at ingest from the free DB-IP database, so countries appear as new visitors arrive (IPs are never stored). If this instance runs with SMOLANALYTICS_GEO=off, that is why."
		}
		if len(unknownV) > 0 {
			// geo ran but resolved nothing to a real country — say so honestly instead
			// of reporting "ZZ", exactly as the dashboard hides an all-Unknown geo card
			return fmt.Sprintf("Geo ran but couldn't resolve any visitor's country — %d visitor(s) came from anonymized/proxy IPs that map to no country (shown as Unknown).%s", len(unknownV), note)
		}
		if win.scoped() {
			return "No geo-stamped pageviews " + win.label + "." + note
		}
		return "No geo-stamped pageviews yet." + note
	}
	type row struct {
		cc       string
		visitors int
	}
	rows := make([]row, 0, len(byCC))
	for cc, a := range byCC {
		rows = append(rows, row{cc, len(a.visitors)})
	}
	sort.Slice(rows, func(i, j int) bool { return rows[i].visitors > rows[j].visitors })
	parts := make([]string, 0, 5)
	for i, r := range rows {
		if i == 5 {
			break
		}
		parts = append(parts, fmt.Sprintf("%s (%d)", r.cc, r.visitors))
	}
	scope := "across all recorded geo data"
	if win.scoped() {
		scope = win.label
	}
	more := ""
	if len(rows) > 5 {
		more = fmt.Sprintf(" and %d more", len(rows)-5)
	}
	noun := "countries"
	if len(rows) == 1 {
		noun = "country"
	}
	unknownNote := ""
	if len(unknownV) > 0 {
		unknownNote = fmt.Sprintf(" (%d more from unresolved/proxy IPs, shown as Unknown)", len(unknownV))
	}
	return fmt.Sprintf("Visitors came from %d %s %s: %s%s.%s%s", len(rows), noun, scope, strings.Join(parts, ", "), more, unknownNote, note)
}
