// ATTACHING A FILE, WITHOUT A FILE.
//
// "Upload a receipt and confirm it appears in the list" is one of the commonest sentences anybody
// wants to write about their own app, and until now this runner could not carry it out at all: the
// agent could see the control (a file input renders as a `button` in the accessibility tree) and
// clicking it did NOTHING — Playwright cancels a file chooser nobody is listening for, so the
// click returned "done", the agent looked at an unchanged page, and reported the upload feature
// broken. A silent no-op that produces a confident bug report about a working app is the worst
// shape a missing feature can take, so this file adds the action AND the note that stops the agent
// clicking these controls.
//
// THE HARD PART IS NOT setInputFiles. IT IS WHICH FILE.
//
// Playwright wants a path on disk. A test that names one — ~/Downloads/receipt.pdf, fixtures/a.png
// committed to the repo — is a test that runs on the laptop it was written on and nowhere else,
// and the entire premise of this product is that a sentence is the whole test: no test code, no
// fixtures directory, nothing written to your repository. So the file is FABRICATED, here, from
// the only statement of intent the page actually makes: the input's `accept` attribute.
//
//   accept="image/*"        → a real 16x16 PNG
//   accept=".pdf"           → a real one-page PDF
//   accept="text/csv"       → a two-row CSV
//   no accept at all        → a short text file
//
// Every one of those is generated byte-for-byte deterministically, which is what makes an upload
// step REPLAYABLE. The recording holds `{kind:"upload", role, name}` and no path and no bytes; at
// replay time the accept attribute is read off the live page again and the same file is rebuilt.
// Storing the fixture in the recording would have put a base64 blob in somebody's repository and
// made the recording lie the moment the app changed what it accepts.
//
// WHY THE IMAGES ARE BUILT AND NOT DOWNLOADED. There are no dependencies in this CLI, so there is
// no image library. The PNG is encoded here (CRC32, an Adler-32, and STORED deflate blocks rather
// than zlib's — deflateSync's output is not promised to be identical across zlib versions, and a
// fixture whose bytes drift between machines is not deterministic). The JPEG cannot be encoded in
// forty lines, so it is a constant: a 16x16 baseline JPEG produced once by Chromium's own encoder
// with its ICC profile stripped, 343 bytes, and browser.test-style tests DECODE it in a real
// browser rather than trusting this comment.

import { mkdirSync, renameSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import { disabledDetail, fileSink, probeControl } from "./uploadsafe.mjs";

/**
 * Where fabricated files go. Never the repository, and never anywhere the app can see by accident.
 *
 * SCOPED TO THE USER. A fixed name under the system temp directory is a directory the FIRST account
 * to run this owns, at 0700, on every shared machine there is — a self-hosted CI runner, a build
 * box, a container that reuses /tmp across jobs. The second account then gets EACCES on the
 * mkdir/write, and because that arrives as a failed upload STEP it reads as a bug in the
 * application under test. Measured: `EACCES: permission denied, open
 * '/tmp/smolanalytics-uploads/smolanalytics-test.png.41958.tmp'` handed to the agent as the reason
 * an upload did not work. The uid costs nothing and the path stays stable per user, which is all
 * the replay path ever needed from it.
 */
const OWNER = typeof process.getuid === "function" ? `-${process.getuid()}` : "";
export const FIXTURE_DIR = path.join(tmpdir(), `smolanalytics-uploads${OWNER}`);

/**
 * The tool the agent is given. `ref` and nothing else: the model does not choose a path, a format
 * or a size, because every one of those is a way for it to invent a file the app then rejects and
 * for the rejection to read as a bug in the app.
 */
export const UPLOAD_TOOL = {
  name: "upload",
  description:
    "Attach a file to a file-upload control — either a file input, or a button that opens a file picker. " +
    "You do NOT choose or name a file: one is generated to match what the control accepts, and the result " +
    "tells you which file was attached. Use this, never click, on anything listed under FILE UPLOADS.",
  input_schema: {
    type: "object",
    properties: { ref: { type: "string" }, why: { type: "string" } },
    required: ["ref", "why"],
    additionalProperties: false,
  },
};

// ---- the files themselves ----------------------------------------------------------------------

const BANNER = "This file was generated by smolanalytics to exercise a file upload in an end-to-end test.";

const TEXT = `${BANNER}\nIt is not a real document and it holds no real data.\n`;
const CSV = `item,quantity,price\nWidget,2,9.99\nGadget,1,24.50\n`;
const JSON_TEXT = `{\n  "source": "smolanalytics",\n  "note": "generated to exercise a file upload in an end-to-end test"\n}\n`;

// A 16x16 baseline JPEG: light grey with a darker square, quality 0.6, APP2/ICC stripped.
// Regenerate with: canvas.toDataURL("image/jpeg", 0.6) in any browser, then drop the 0xFFE2 segment.
// Proved to decode at 16x16 by a real browser in test/upload.test.mjs — not by this comment.
const JPEG_B64 =
  "/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAA0JCgsKCA0LCgsODg0PEyAVExISEyccHhcgLikxMC4pLSwzOko+Mz" +
  "ZGNywtQFdBRkxOUlNSMj5aYVpQYEpRUk//2wBDAQ4ODhMREyYVFSZPNS01T09PT09PT09PT09PT09PT09PT09P" +
  "T09PT09PT09PT09PT09PT09PT09PT09PT09PT0//wAARCAAQABADASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAA" +
  "AAAAAAAAX/xAAeEAAABAcAAAAAAAAAAAAAAAAFERITAAEVJEJRYf/EABQBAQAAAAAAAAAAAAAAAAAAAAD/xAAU" +
  "EQEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIRAxEAPwC+PjlGYtnnlZpIi5PcAAcrL9syynNRmfJagPgdZYuWWV" +
  "YKMy7LUAADoz9y88nBJEfZ7gP/2Q==";

// --- PNG, encoded here because there is no image library and there will not be one --------------

const CRC_TABLE = (() => {
  const t = new Int32Array(256);
  for (let n = 0; n < 256; n++) {
    let c = n;
    for (let k = 0; k < 8; k++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
    t[n] = c;
  }
  return t;
})();

function crc32(buf) {
  let c = -1;
  for (let i = 0; i < buf.length; i++) c = CRC_TABLE[(c ^ buf[i]) & 0xff] ^ (c >>> 8);
  return (c ^ -1) >>> 0;
}

function adler32(buf) {
  let a = 1;
  let b = 0;
  for (let i = 0; i < buf.length; i++) {
    a = (a + buf[i]) % 65521;
    b = (b + a) % 65521;
  }
  return ((b << 16) | a) >>> 0;
}

function pngChunk(type, data) {
  const out = Buffer.alloc(12 + data.length);
  out.writeUInt32BE(data.length, 0);
  out.write(type, 4, "ascii");
  data.copy(out, 8);
  out.writeUInt32BE(crc32(out.subarray(4, 8 + data.length)), 8 + data.length);
  return out;
}

/**
 * A zlib stream of STORED (uncompressed) deflate blocks.
 *
 * zlib.deflateSync would be four characters instead of fifteen lines, and its bytes are not
 * promised to be identical across zlib builds. A fixture whose content depends on which Node the
 * runner happens to have is not deterministic, and "regenerated deterministically at replay time"
 * is the property that lets an upload step be replayed without a model.
 */
function storedDeflate(raw) {
  const parts = [Buffer.from([0x78, 0x01])]; // CMF/FLG, and (0x78 * 256 + 0x01) % 31 === 0
  const MAX = 65535;
  let off = 0;
  do {
    const slice = raw.subarray(off, Math.min(off + MAX, raw.length));
    const last = off + MAX >= raw.length ? 1 : 0;
    const head = Buffer.alloc(5);
    head[0] = last;
    head.writeUInt16LE(slice.length, 1);
    head.writeUInt16LE(~slice.length & 0xffff, 3);
    parts.push(head, slice);
    off += MAX;
    if (last) break;
  } while (off < raw.length + MAX);
  const tail = Buffer.alloc(4);
  tail.writeUInt32BE(adler32(raw), 0);
  parts.push(tail);
  return Buffer.concat(parts);
}

/** An 8-bit greyscale PNG: a light field with a darker square, so a human who opens it can see it. */
export function pngBytes(w = 16, h = 16) {
  const raw = Buffer.alloc(h * (1 + w));
  for (let y = 0; y < h; y++) {
    const row = y * (1 + w);
    raw[row] = 0; // filter: none
    for (let x = 0; x < w; x++) {
      const inner = x >= w / 4 && x < (w * 3) / 4 && y >= h / 4 && y < (h * 3) / 4;
      raw[row + 1 + x] = inner ? 0x40 : 0xd8;
    }
  }
  const ihdr = Buffer.alloc(13);
  ihdr.writeUInt32BE(w, 0);
  ihdr.writeUInt32BE(h, 4);
  ihdr[8] = 8; // bit depth
  ihdr[9] = 0; // colour type: greyscale
  return Buffer.concat([
    Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]),
    pngChunk("IHDR", ihdr),
    pngChunk("IDAT", storedDeflate(raw)),
    pngChunk("IEND", Buffer.alloc(0)),
  ]);
}

// --- PDF, assembled with real cross-reference offsets ------------------------------------------

/**
 * A one-page PDF that says what it is.
 *
 * The xref table is the part people get wrong: every entry is a BYTE OFFSET of the object it names
 * and every entry is exactly twenty bytes wide, so a hand-written PDF with a hardcoded table stops
 * being readable the moment anybody edits a string in it. These offsets are measured off the bytes
 * as they are assembled, and test/upload.test.mjs walks the finished table and checks that each
 * offset really lands on "<n> 0 obj".
 */
export function pdfBytes() {
  const body =
    "BT /F1 12 Tf 24 150 Td (smolanalytics test upload) Tj ET\n" +
    "BT /F1 9 Tf 24 130 Td (Generated for an end-to-end test. Not a real document.) Tj ET\n";
  const objects = [
    "<< /Type /Catalog /Pages 2 0 R >>",
    "<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
    "<< /Type /Page /Parent 2 0 R /MediaBox [0 0 300 200] /Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >>",
    `<< /Length ${body.length} >>\nstream\n${body}endstream`,
    "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
  ];
  let out = "%PDF-1.4\n";
  const offsets = [];
  objects.forEach((o, i) => {
    offsets.push(out.length);
    out += `${i + 1} 0 obj\n${o}\nendobj\n`;
  });
  const startxref = out.length;
  out += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`;
  // Twenty bytes per entry, exactly: ten digits, space, five digits, space, "n", space, newline.
  for (const off of offsets) out += `${String(off).padStart(10, "0")} 00000 n \n`;
  out += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${startxref}\n%%EOF\n`;
  return Buffer.from(out, "latin1");
}

// ---- picking one, from `accept` ----------------------------------------------------------------

const KINDS = {
  png: { ext: "png", what: "a 16x16 PNG", make: () => pngBytes() },
  jpeg: { ext: "jpg", what: "a 16x16 JPEG", make: () => Buffer.from(JPEG_B64, "base64") },
  pdf: { ext: "pdf", what: "a one-page PDF", make: () => pdfBytes() },
  csv: { ext: "csv", what: "a three-line CSV", make: () => Buffer.from(CSV, "utf8") },
  json: { ext: "json", what: "a small JSON file", make: () => Buffer.from(JSON_TEXT, "utf8") },
  txt: { ext: "txt", what: "a short text file", make: () => Buffer.from(TEXT, "utf8") },
};

// The tokens an `accept` attribute is actually written with, in the wild. Order inside the
// attribute decides, not order here: an input that says ".pdf,.png" is asking for a PDF first.
const BY_TOKEN = new Map([
  ["image/png", "png"], [".png", "png"],
  ["image/jpeg", "jpeg"], ["image/jpg", "jpeg"], [".jpg", "jpeg"], [".jpeg", "jpeg"],
  ["image/*", "png"],
  ["application/pdf", "pdf"], [".pdf", "pdf"],
  ["text/csv", "csv"], ["application/csv", "csv"], [".csv", "csv"],
  ["application/json", "json"], [".json", "json"],
  ["text/plain", "txt"], ["text/*", "txt"], [".txt", "txt"], [".text", "txt"],
  ["*/*", "txt"], ["application/octet-stream", "txt"],
]);

/**
 * The safe part of a token used as a filename extension, which is why no `accept` a page can write
 * ever reaches the filesystem: everything but [a-z0-9] is dropped and anything over eight
 * characters is refused outright. Measured — ".doc x" → "docx", "app/vnd.foo" → "vndfoo",
 * "../../../etc/passwd" → "" (nine characters after cleaning), ".png\0.exe" → "pngexe".
 */
function extFrom(token) {
  const raw = token.startsWith(".") ? token.slice(1) : (token.split("/")[1] || "");
  const clean = raw.replace(/[^a-z0-9]/g, "");
  return clean && clean.length <= 8 ? clean : "";
}

/**
 * Which file to fabricate for an `accept` attribute. A PURE FUNCTION of that string, which is the
 * whole reason an upload can be replayed: the same page produces the same bytes on every run, on
 * every machine, forever.
 */
export function fixtureFor(accept) {
  const raw = String(accept == null ? "" : accept).trim();
  const tokens = raw ? raw.split(",").map((t) => t.trim().toLowerCase()).filter(Boolean) : [];

  for (const token of tokens) {
    const kind = BY_TOKEN.get(token);
    if (!kind) continue;
    return build(kind, raw, `the control accepts ${JSON.stringify(raw)}`);
  }

  if (!tokens.length) {
    return build("txt", raw, "the control names no accept attribute, so any file will do");
  }

  // BEFORE IMPROVISING, CHECK THE EXTENSION. `accept="text/json"` and `accept="image/pdf"` are both
  // written in the wild and neither is a token in the table above, so both used to fall through to
  // the improvised branch and be handed a plain text file — named `.json` and `.pdf` — while a real
  // JSON and a real PDF sat two lines away in KINDS. Two things went wrong with that:
  //
  //   the app is right to reject it   an uploader that parses what it is given says no to a .json
  //                                   holding "This file was generated by smolanalytics…", and that
  //                                   rejection reads as a bug in a working upload flow.
  //   two files, one path             FIXTURE_DIR is a stable shared directory, so improvised
  //                                   `.pdf` and real `.pdf` are the SAME PATH with DIFFERENT
  //                                   bytes. writeFixture's rename is atomic but atomicity is not
  //                                   the property that was needed — measured, `image/pdf` and
  //                                   `application/pdf` produced sha256 b15c63d1… and 85e4c40f… at
  //                                   one path, so with --workers > 1 one test's PDF could be read
  //                                   as another's text file.
  //
  // So the extension gets one more look-up before anything is improvised. After this, a fixture's
  // NAME is a function of its KIND, which makes the shared directory safe again.
  const known = extFrom(tokens[0]) ? BY_TOKEN.get(`.${extFrom(tokens[0])}`) : null;
  if (known) return build(known, raw, `the control accepts ${JSON.stringify(raw)}`);

  // AN ACCEPT WE CANNOT HONOUR — .docx, .heic, video/mp4. Fabricating a real one of those is out of
  // reach, and there are exactly two honest options: refuse the upload, or attach something with
  // the right name and SAY that the contents are not what was asked for. Refusing would report
  // "this runner cannot test your upload" for a form that might well accept it; attaching in
  // silence would report the app's own correct rejection as a bug in the app. So: attach, and put
  // the caveat in the step label and in what the agent is told, where whoever reads the verdict
  // sees it.
  const ext = extFrom(tokens[0]) || "txt";
  const f = build("txt", raw, `the control accepts ${JSON.stringify(raw)}, which this runner cannot fabricate`);
  return {
    ...f,
    name: `smolanalytics-test.${ext}`,
    improvised: true,
    why:
      `${f.why}, so a plain text file named .${ext} was attached instead — if the app rejects it, ` +
      `that is about this fixture, not about your upload flow`,
  };
}

function build(kind, accept, why) {
  const k = KINDS[kind];
  return {
    kind,
    name: `smolanalytics-test.${k.ext}`,
    bytes: k.make(),
    accept,
    improvised: false,
    why: `${k.what}, because ${why}`,
  };
}

/**
 * Fabricate the file and put it on disk.
 *
 * The path is stable — same accept, same path, same bytes — so nothing accumulates and a replay
 * lands on the identical file. Written beside and renamed into place because two suites running at
 * once would otherwise be able to read one another's half-written file; rename is atomic within a
 * filesystem, and both writers are writing identical content anyway.
 */
export function writeFixture(accept, dir = FIXTURE_DIR) {
  const f = fixtureFor(accept);
  mkdirSync(dir, { recursive: true });
  const full = path.join(dir, f.name);
  const tmp = `${full}.${process.pid}.tmp`;
  writeFileSync(tmp, f.bytes);
  renameSync(tmp, full);
  return { ...f, path: full };
}

/**
 * writeFixture, with the one failure it has said in OUR words.
 *
 * WHY. Everything performUpload returns as {ok:false} is handed to the agent as the reason a step
 * did not work, and the agent's job is to decide whether the APPLICATION is broken. `EACCES:
 * permission denied, open '/tmp/smolanalytics-uploads/smolanalytics-test.png.31.tmp'` is not a fact
 * about the application at all — it is our own scratch directory, and a reviewer reading a red
 * check caused by it would go looking through their upload handler. Measured on a directory owned
 * by another account, which is what a shared CI runner hands you.
 *
 * `runner: true` marks it as ours for any caller that wants to route it; nothing routes on it
 * today, and no status or exit code changes here — the sentence is the fix, and it is the part
 * that reaches the verdict.
 */
function makeFixture(accept, dir) {
  try {
    return { file: writeFixture(accept, dir) };
  } catch (e) {
    return {
      runner: true,
      detail:
        `smolanalytics could not create the file to upload in ${dir} (${firstLine(e)}). ` +
        `That is this test runner's own temporary directory, not anything about the app under test.`,
    };
  }
}

/** The sentence that goes in the step label, the terminal, and what the agent is told. */
export function uploadLabel(file) {
  if (!file) return "";
  return `attached ${file.name} (${file.why})`;
}

// ---- doing it in the browser -------------------------------------------------------------------

/**
 * What kind of control this is: a file input we can hand files to directly, or a button that opens
 * a picker. Returns {accept, via, disabled} for the direct case, and null for everything else.
 *
 * See lib/uploadsafe.mjs, which owns this and the three measured defects it exists to fix:
 * setInputFiles refuses a <label> and a wrapper (so the file goes to the input INSIDE them), the
 * probe must honour the caller's timeout (30s of Playwright's default, on top of the click, made a
 * missing control cost 40s), and a disabled input must be refused rather than silently uploaded to.
 */
const directAccept = (locator, timeout) => probeControl(locator, timeout);

/**
 * Attach a fabricated file to whatever `locator` points at.
 *
 * Never throws: the caller's contract (lib/test.mjs act()) is {ok, detail}, and a step that fails
 * is a thing the agent judges, not an error in the runner.
 */
export async function performUpload(page, locator, { dir = FIXTURE_DIR, timeout = 10_000 } = {}) {
  try {
    const direct = await directAccept(locator, timeout);
    if (direct) {
      // A control no user could use is not one to report as uploaded to. lib/uploadsafe.mjs.
      if (direct.disabled) return { ok: false, detail: disabledDetail() };
      const made = makeFixture(direct.accept, dir);
      if (!made.file) return { ok: false, detail: made.detail, runner: true };
      // The INPUT, which for a label or a styled wrapper is not the element the agent named.
      await fileSink(locator, direct.via).setInputFiles(made.file.path, { timeout });
      return { ok: true, file: made.file, note: uploadLabel(made.file) };
    }

    // A BUTTON THAT OPENS A PICKER. allSettled, not Promise.all: when the chooser never arrives,
    // all() rejects on the timeout and the click's own later rejection becomes an unhandled one,
    // which in a Node test run kills the process rather than failing a step.
    const [event, clicked] = await Promise.allSettled([
      page.waitForEvent("filechooser", { timeout }),
      locator.click({ timeout }),
    ]);
    if (clicked.status === "rejected") return { ok: false, detail: firstLine(clicked.reason) };
    if (event.status === "rejected") {
      return {
        ok: false,
        detail:
          `clicking it did not open a file picker within ${Math.round(timeout / 1000)}s, so no file was attached — ` +
          `if this control only takes a drag-and-drop, this runner cannot use it`,
      };
    }
    const chooser = event.value;
    // The accept lives on the input the chooser came from, which is usually the hidden one the
    // button clicks. Reading it here is the only way a styled uploader gets the right file type.
    const accept = await chooser
      .element()
      .evaluate((n) => n.accept || "")
      .catch(() => "");
    const made = makeFixture(accept, dir);
    if (!made.file) return { ok: false, detail: made.detail, runner: true };
    await chooser.setFiles(made.file.path, { timeout });
    return { ok: true, file: made.file, note: uploadLabel(made.file) };
  } catch (e) {
    return { ok: false, detail: firstLine(e) };
  }
}

const firstLine = (e) => String(e && e.message ? e.message : e).split("\n")[0];

// ---- telling the agent these controls are here -------------------------------------------------

/**
 * The file inputs on the page.
 *
 * WHY THE AGENT HAS TO BE TOLD. A file input's accessibility role is `button`, indistinguishable
 * in the ELEMENTS list from any other button — and clicking one is a SILENT no-op, because
 * Playwright cancels a file chooser that nobody is listening for. Measured in a real Chromium: the
 * click reports "done", the page is unchanged, and the agent concludes the upload feature is
 * broken. So perception names them and the note says which tool to use.
 *
 * Never throws, and returns [] on any trouble: perception is how the agent sees, and a page that
 * navigated mid-read must cost us this note, never the verdict.
 */
export async function uploadTargets(page) {
  // EVERY FRAME, not just the main document. An upload widget is one of the things most often
  // shipped as an embed, and lib/frames.mjs exists because a whole payment form rendering as the
  // single word "iframe" cost this runner a verdict once already. perceive() can already SEE and
  // act on a control inside a frame, so a note that stopped at the main document would name no
  // upload on exactly the pages where the agent most needs telling.
  const read = (frame) =>
    frame
      .evaluate(() =>
        [...document.querySelectorAll("input[type=file]")].slice(0, 12).map((i) => {
          const label = i.labels && i.labels.length ? i.labels[0].textContent : "";
          const name = String(label || i.getAttribute("aria-label") || i.name || "").replace(/\s+/g, " ").trim();
          return { name: name.slice(0, 80), accept: String(i.accept || "").slice(0, 80) };
        }),
      )
      .catch(() => []);
  try {
    const frames = typeof page.frames === "function" ? page.frames() : [page];
    const per = await Promise.all(frames.slice(0, 8).map(read));
    return per.flat().slice(0, 12);
  } catch {
    return [];
  }
}

/**
 * The FILE UPLOADS block for render(). [] when the page has none, which is almost every page — so
 * this adds not one character to the ordinary case.
 */
export function uploadNotes(targets) {
  const list = Array.isArray(targets) ? targets.filter((t) => t && typeof t === "object") : [];
  if (!list.length) return [];
  const named = list
    .slice(0, 6)
    .map((t) => `${t.name ? JSON.stringify(String(t.name)) : "an unnamed control"} (accepts ${t.accept ? String(t.accept) : "any file"})`);
  const more = list.length > named.length ? `, and ${list.length - named.length} more` : "";
  return [
    `FILE UPLOADS on this page: ${named.join("; ")}${more}.`,
    "Use the upload tool on these, never click — clicking a file input does nothing at all. A file is generated for you.",
    "",
  ];
}
